import type { ModelLimit, ModelPricing } from 'chrome-tab-shared'
import type { BaselineModel } from './modelTracking'

/**
 * OpenAI 人工核验基线(issues/03)。全部资料于 2026-08-25 自官方一手信源核对:
 * - 模型清单/上下文/最大输出/模态:模型目录 developers.openai.com/api/docs/models.md
 *   及各模型文档页(.md 逐个核验,96 条目录 ID)
 * - 价格(美元,标准档):官方价格页 developers.openai.com/api/docs/pricing.md
 * - 动态(上线日期):API changelog developers.openai.com/api/docs/changelog.md
 * - 弃用/退役(公告日与关停日):弃用页 developers.openai.com/api/docs/deprecations.md
 * - 开放权重:HuggingFace 官方 org openai 实仓(参数量取自官方 README)
 * 归并规则(issues/03):独立命名型号/变体各立一行;移动别名(chat-latest、
 * gpt-5.x-chat-latest、chatgpt-4o-latest、chatgpt-image-latest、daybreak-*-latest)
 * 与日期快照(gpt-image-2-2026-04-21、sora-2-2025-10-06 等)不另占行——快照经
 * matchAliases 前缀归族。目录未列独立 rerank 模型(研究 §4),基线无 rerank 行;
 * GPT 主线模型的图像输入是能力不是种类,均为 text。gpt-5.6-cyber 仅随 Daybreak
 * 计划获批提供;gpt-oss-safeguard 两型号仅开放权重(不在 API 目录,changelog 记录)。
 * 收录边界:当前目录全部条目 + 弃用页 2025 年后有官方记录的已退役模型
 * (dall-e-2/3、codex-mini-latest 等);更早(completions 时代的 GPT-3 系)不回填。
 * 无上线事件的行 = 发布早于 changelog 覆盖范围(tts/whisper/embedding 前代等),
 * 官方 API 信源无日期可证,不臆造。
 */

/** 平台/地区作用域(全部现价均为 OpenAI API 美元标准档)。 */
const API = 'OpenAI API(美元)'
const PRICING_PAGE = { title: '官方价格页', url: 'https://developers.openai.com/api/docs/pricing' }
const DEPRECATIONS_PAGE = { title: '官方弃用页', url: 'https://developers.openai.com/api/docs/deprecations' }
const CHANGELOG_URL = 'https://developers.openai.com/api/docs/changelog'
const CHANGELOG_PAGE = { title: 'API Changelog', url: CHANGELOG_URL }
const DOC = (id: string) => `https://developers.openai.com/api/docs/models/${id}`
/** 开放权重信源(HuggingFace 官方 openai 实仓)。 */
const HF = (repo: string) => ({ title: `开放权重(HuggingFace openai/${repo})`, url: `https://huggingface.co/openai/${repo}` })
const OPENAI_MONTHS = ['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec'] as const

/** changelog 页基址(人类可读页;轮询抓取的 .md 形态由 modelTracking 以 `+ '.md'` 派生,单一事实源)。 */
export const OPENAI_CHANGELOG_PAGE_URL = CHANGELOG_URL

/**
 * changelog 日期锚点(`#mon-d` 格式):基线事件与 modelTracking 的 changelog 解析器
 * **共用此函数**——同公告去重键的公共信源串,两处拼串漂移即去重失效(issues/02 的
 * eventKey 共享教训;开发期锚点月份曾差一,即此类 bug)。
 */
export function openaiChangelogAnchor(date: string): string {
  return `${CHANGELOG_URL}#${OPENAI_MONTHS[Number(date.slice(5, 7)) - 1]!}-${Number(date.slice(8, 10))}`
}
const CL = openaiChangelogAnchor

const price = (entries: ModelPricing['entries']): ModelPricing => ({ region: API, effectiveFrom: null, entries })
/** 百万 tokens 标准价(输入/输出;scope 为官方档位原文,如 '>272K tokens')。 */
const perM = (input: string, output: string, scope: string | null = null): ModelPricing =>
  price([{ text: `输入 $${input}/百万 tokens`, scope }, { text: `输出 $${output}/百万 tokens`, scope }])
/** 短/长上下文双档价(官方 '<272K / >272K context length' 口径)。 */
const perMTiers = (sIn: string, sOut: string, lIn: string, lOut: string): ModelPricing =>
  price([...perM(sIn, sOut, '≤272K context length').entries, ...perM(lIn, lOut, '>272K context length').entries])
/** 多模态逐档价(如 realtime 的 audio/text/image 各档)。 */
const perModality = (...rows: Array<[string, string]>): ModelPricing =>
  price(rows.map(([scope, text]) => ({ text, scope })))
/** 「上下文/最大输出」限额对(模型文档页原文数值)。 */
const ctx = (context: string, maxOut: string): ModelLimit[] => [
  { label: '上下文窗口', text: context, scope: null },
  { label: '最大输出', text: maxOut, scope: null },
]

export const OPENAI_BASELINE: BaselineModel[] = [
  // ---- 文本(GPT-5.6 → 5.4 世代;均为 API 美元标准档价)----
  {
    provider: 'openai',
    officialId: 'gpt-5.6-sol',
    name: 'GPT-5.6 Sol',
    kind: 'text',
    stage: 'ga',
    availability: ['api', 'first_party_app'],
    summary: 'GPT-5.6 世代旗舰:面向复杂专业工作的前沿模型,gpt-5.6 别名路由至此',
    sources: [
      { title: 'GPT-5.6 Sol 模型文档', url: DOC('gpt-5.6-sol') },
      PRICING_PAGE,
      CHANGELOG_PAGE,
    ],
    pricing: perMTiers('4.00', '20.00', '8.00', '30.00'),
    limits: ctx('1,050,000', '128,000'),
    trainingParams: null,
    matchAliases: ['gpt-5.6-sol', 'gpt-5.6'], // gpt-5.6 家族别名路由至此(changelog 口径)
    events: [
      { kind: 'api_available', occurredOn: '2026-07-09', title: 'GPT-5.6 模型家族上线 API(Sol/Terra/Luna)', sourceUrl: CL('2026-07-09') },
      { kind: 'first_party_available', occurredOn: '2026-08-06', title: 'GPT-5.6 Sol 在 ChatGPT 内改进', sourceUrl: 'https://openai.com/index/improving-gpt-5-6-sol-in-chatgpt' },
      { kind: 'updated', occurredOn: '2026-08-21', title: 'GPT-5.6 Sol 降价:输入 $4/输出 $20 每百万 tokens(促销价至少持续至 2026-11-21)', sourceUrl: CL('2026-08-21') },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-5.6-terra',
    name: 'GPT-5.6 Terra',
    kind: 'text',
    stage: 'ga',
    availability: ['api'],
    summary: 'GPT-5.6 世代均衡档:智能与成本兼顾',
    sources: [
      { title: 'GPT-5.6 Terra 模型文档', url: DOC('gpt-5.6-terra') },
      PRICING_PAGE,
      CHANGELOG_PAGE,
    ],
    pricing: perMTiers('2.00', '12.00', '4.00', '18.00'),
    limits: ctx('1,050,000', '128,000'),
    trainingParams: null,
    matchAliases: ['gpt-5.6-terra'],
    events: [
      { kind: 'api_available', occurredOn: '2026-07-09', title: 'GPT-5.6 模型家族上线 API(Sol/Terra/Luna)', sourceUrl: CL('2026-07-09') },
      { kind: 'updated', occurredOn: '2026-07-30', title: 'GPT-5.6 Terra 降价 20%', sourceUrl: CL('2026-07-30') },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-5.6-luna',
    name: 'GPT-5.6 Luna',
    kind: 'text',
    stage: 'ga',
    availability: ['api', 'first_party_app'],
    summary: 'GPT-5.6 世代成本档:面向成本敏感、高吞吐负载',
    sources: [
      { title: 'GPT-5.6 Luna 模型文档', url: DOC('gpt-5.6-luna') },
      PRICING_PAGE,
      CHANGELOG_PAGE,
    ],
    pricing: perMTiers('0.20', '1.20', '0.40', '1.80'),
    limits: ctx('1,050,000', '128,000'),
    trainingParams: null,
    matchAliases: ['gpt-5.6-luna'],
    events: [
      { kind: 'api_available', occurredOn: '2026-07-09', title: 'GPT-5.6 模型家族上线 API(Sol/Terra/Luna)', sourceUrl: CL('2026-07-09') },
      { kind: 'updated', occurredOn: '2026-07-30', title: 'GPT-5.6 Luna 降价 80%', sourceUrl: CL('2026-07-30') },
      { kind: 'first_party_available', occurredOn: '2026-08-06', title: 'GPT-5.6 Luna 向 ChatGPT 免费用户开放', sourceUrl: 'https://openai.com/index/improving-gpt-5-6-sol-in-chatgpt' },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-5.6-cyber',
    name: 'GPT-5.6 Cyber',
    kind: 'text',
    stage: 'ga',
    availability: ['api'],
    summary: '面向授权漏洞研究与安全测试的网络安全专用模型(随 Daybreak Red 计划获批提供)',
    sources: [
      { title: 'GPT-5.6 Cyber 模型文档', url: DOC('gpt-5.6-cyber') },
      PRICING_PAGE,
      CHANGELOG_PAGE,
    ],
    pricing: perM('12.50', '75.00'),
    limits: ctx('400,000', '128,000'),
    trainingParams: null,
    matchAliases: ['gpt-5.6-cyber'],
    events: [
      { kind: 'updated', occurredOn: '2026-08-07', title: 'Daybreak 分两档访问:Red 档提供 GPT-5.6 Cyber 专用安全模型', sourceUrl: CL('2026-08-07') },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-5.5',
    name: 'GPT-5.5',
    kind: 'text',
    stage: 'ga',
    availability: ['api'],
    summary: '面向复杂专业工作的新智能级模型,1M 上下文,默认推理力度 medium',
    sources: [
      { title: 'GPT-5.5 模型文档', url: DOC('gpt-5.5') },
      PRICING_PAGE,
      CHANGELOG_PAGE,
    ],
    pricing: perMTiers('5.00', '30.00', '10.00', '45.00'),
    limits: ctx('1,050,000', '128,000'),
    trainingParams: null,
    matchAliases: ['gpt-5.5'],
    events: [
      { kind: 'api_available', occurredOn: '2026-04-24', title: 'GPT-5.5 上线(新智能级,1M 上下文)', sourceUrl: CL('2026-04-24') },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-5.5-pro',
    name: 'GPT-5.5 Pro',
    kind: 'text',
    stage: 'ga',
    availability: ['api'],
    summary: 'GPT-5.5 的 Pro 版本:更多算力换取更聪明、更精确的回答(Responses API)',
    sources: [
      { title: 'GPT-5.5 Pro 模型文档', url: DOC('gpt-5.5-pro') },
      PRICING_PAGE,
      CHANGELOG_PAGE,
    ],
    pricing: perMTiers('30.00', '180.00', '60.00', '270.00'),
    limits: ctx('1,050,000', '128,000'),
    trainingParams: null,
    matchAliases: ['gpt-5.5-pro'],
    events: [
      { kind: 'api_available', occurredOn: '2026-04-24', title: 'GPT-5.5 Pro 上线', sourceUrl: CL('2026-04-24') },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-5.4',
    name: 'GPT-5.4',
    kind: 'text',
    stage: 'ga',
    availability: ['api'],
    summary: '更平价的专业工作模型:1M 上下文、内置计算机使用与压缩(compaction)',
    sources: [
      { title: 'GPT-5.4 模型文档', url: DOC('gpt-5.4') },
      PRICING_PAGE,
      CHANGELOG_PAGE,
    ],
    pricing: perMTiers('2.50', '15.00', '5.00', '22.50'),
    limits: ctx('1,050,000', '128,000'),
    trainingParams: null,
    matchAliases: ['gpt-5.4'],
    events: [
      { kind: 'api_available', occurredOn: '2026-03-05', title: 'GPT-5.4 上线(新前沿模型,1M 上下文)', sourceUrl: CL('2026-03-05') },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-5.4-pro',
    name: 'GPT-5.4 Pro',
    kind: 'text',
    stage: 'ga',
    availability: ['api'],
    summary: 'GPT-5.4 的 Pro 版本:更多算力换取更聪明的回答',
    sources: [
      { title: 'GPT-5.4 Pro 模型文档', url: DOC('gpt-5.4-pro') },
      PRICING_PAGE,
      CHANGELOG_PAGE,
    ],
    pricing: perMTiers('30.00', '180.00', '60.00', '270.00'),
    limits: ctx('1,050,000', '128,000'),
    trainingParams: null,
    matchAliases: ['gpt-5.4-pro'],
    events: [
      { kind: 'api_available', occurredOn: '2026-03-05', title: 'GPT-5.4 Pro 上线', sourceUrl: CL('2026-03-05') },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-5.4-mini',
    name: 'GPT-5.4 Mini',
    kind: 'text',
    stage: 'ga',
    availability: ['api'],
    summary: '最强 mini 档:编程、计算机使用与子代理负载的效率之选',
    sources: [
      { title: 'GPT-5.4 Mini 模型文档', url: DOC('gpt-5.4-mini') },
      PRICING_PAGE,
      CHANGELOG_PAGE,
    ],
    pricing: perM('0.75', '4.50'),
    limits: ctx('400,000', '128,000'),
    trainingParams: null,
    matchAliases: ['gpt-5.4-mini'],
    events: [
      { kind: 'api_available', occurredOn: '2026-03-17', title: 'GPT-5.4 mini 与 nano 上线', sourceUrl: CL('2026-03-17') },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-5.4-nano',
    name: 'GPT-5.4 nano',
    kind: 'text',
    stage: 'ga',
    availability: ['api'],
    summary: 'GPT-5.4 级最便宜档:简单高吞吐任务',
    sources: [
      { title: 'GPT-5.4 nano 模型文档', url: DOC('gpt-5.4-nano') },
      PRICING_PAGE,
      CHANGELOG_PAGE,
    ],
    pricing: perM('0.20', '1.25'),
    limits: ctx('400,000', '128,000'),
    trainingParams: null,
    matchAliases: ['gpt-5.4-nano'],
    events: [
      { kind: 'api_available', occurredOn: '2026-03-17', title: 'GPT-5.4 mini 与 nano 上线', sourceUrl: CL('2026-03-17') },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-5.3-codex',
    name: 'GPT-5.3-Codex',
    kind: 'text',
    stage: 'ga',
    availability: ['api'],
    summary: '迄今最强 agentic 编程模型(Responses API)',
    sources: [
      { title: 'GPT-5.3-Codex 模型文档', url: DOC('gpt-5.3-codex') },
      PRICING_PAGE,
      CHANGELOG_PAGE,
    ],
    pricing: perM('1.75', '14.00'),
    limits: ctx('400,000', '128,000'),
    trainingParams: null,
    matchAliases: ['gpt-5.3-codex'],
    events: [
      { kind: 'api_available', occurredOn: '2026-02-24', title: 'gpt-5.3-codex 上线 Responses API', sourceUrl: CL('2026-02-24') },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-5.2',
    name: 'GPT-5.2',
    kind: 'text',
    stage: 'ga',
    availability: ['api'],
    summary: '上一代旗舰:指令遵循、视觉与代码生成(尤其前端 UI)全面超越 5.1,xhigh 推理档',
    sources: [
      { title: 'GPT-5.2 模型文档', url: DOC('gpt-5.2') },
      PRICING_PAGE,
      CHANGELOG_PAGE,
    ],
    pricing: perM('1.75', '14.00'),
    limits: ctx('400,000', '128,000'),
    trainingParams: null,
    matchAliases: ['gpt-5.2'],
    events: [
      { kind: 'api_available', occurredOn: '2025-12-11', title: 'GPT-5.2 上线(GPT-5 家族最新旗舰)', sourceUrl: CL('2025-12-11') },
      { kind: 'updated', occurredOn: '2026-02-03', title: '推理栈优化:GPT-5.2 与 GPT-5.2-Codex 提速约 40%(模型与权重不变)', sourceUrl: CL('2026-02-03') },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-5.2-pro',
    name: 'GPT-5.2 Pro',
    kind: 'text',
    stage: 'ga',
    availability: ['api'],
    summary: 'GPT-5.2 的 Pro 版本:更多算力换取更聪明的回答',
    sources: [
      { title: 'GPT-5.2 Pro 模型文档', url: DOC('gpt-5.2-pro') },
      PRICING_PAGE,
    ],
    pricing: perM('21.00', '168.00'),
    limits: ctx('400,000', '128,000'),
    trainingParams: null,
    matchAliases: ['gpt-5.2-pro'],
    events: [
      // 与 5.2 同日发布(默认快照 gpt-5.2-pro-2025-12-11,模型文档页口径)
      { kind: 'api_available', occurredOn: '2025-12-11', title: 'GPT-5.2 Pro 上线', sourceUrl: DOC('gpt-5.2-pro') },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-5.2-codex',
    name: 'GPT-5.2-Codex',
    kind: 'text',
    stage: 'retired',
    availability: ['api'],
    summary: 'GPT-5.2 的 agentic 编程变体(曾为最强编程模型),2026-07-23 已关停',
    sources: [
      { title: 'GPT-5.2-Codex 模型文档', url: DOC('gpt-5.2-codex') },
      DEPRECATIONS_PAGE,
    ],
    pricing: null, // 关停后官方价格页已不列
    limits: ctx('400,000', '128,000'),
    trainingParams: null,
    matchAliases: ['gpt-5.2-codex'],
    events: [
      { kind: 'api_available', occurredOn: '2026-01-14', title: 'gpt-5.2-codex 上线 Responses API', sourceUrl: CL('2026-01-14') },
      { kind: 'deprecated', occurredOn: '2026-04-22', title: '弃用公告:2026-07-23 关停(替代 gpt-5.6-sol)', sourceUrl: DEPRECATIONS_PAGE.url },
      { kind: 'retired', occurredOn: '2026-07-23', title: '已从 API 关停', sourceUrl: DEPRECATIONS_PAGE.url },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-5.1',
    name: 'GPT-5.1',
    kind: 'text',
    stage: 'ga',
    availability: ['api'],
    summary: '可配推理力度(none 默认)的编程与 agentic 任务旗舰,指令遵循与响应速度增强',
    sources: [
      { title: 'GPT-5.1 模型文档', url: DOC('gpt-5.1') },
      PRICING_PAGE,
      CHANGELOG_PAGE,
    ],
    pricing: perM('1.25', '10.00'),
    limits: ctx('400,000', '128,000'),
    trainingParams: null,
    matchAliases: ['gpt-5.1'],
    events: [
      { kind: 'api_available', occurredOn: '2025-11-13', title: 'GPT-5.1 上线(新旗舰,推理默认 none 档)', sourceUrl: CL('2025-11-13') },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-5.1-codex',
    name: 'GPT-5.1-Codex',
    kind: 'text',
    stage: 'retired',
    availability: ['api'],
    summary: 'GPT-5.1 的 agentic 编程变体,2026-07-23 已关停',
    sources: [
      { title: 'GPT-5.1-Codex 模型文档', url: DOC('gpt-5.1-codex') },
      DEPRECATIONS_PAGE,
    ],
    pricing: null,
    limits: ctx('400,000', '128,000'),
    trainingParams: null,
    matchAliases: ['gpt-5.1-codex'],
    events: [
      { kind: 'api_available', occurredOn: '2025-11-13', title: 'gpt-5.1-codex 与 gpt-5.1-codex-mini 上线', sourceUrl: CL('2025-11-13') },
      { kind: 'deprecated', occurredOn: '2026-04-22', title: '弃用公告:2026-07-23 关停(替代 gpt-5.6-sol)', sourceUrl: DEPRECATIONS_PAGE.url },
      { kind: 'retired', occurredOn: '2026-07-23', title: '已从 API 关停', sourceUrl: DEPRECATIONS_PAGE.url },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-5.1-codex-mini',
    name: 'GPT-5.1-Codex Mini',
    kind: 'text',
    stage: 'retired',
    availability: ['api'],
    summary: '更小更省的 GPT-5.1-Codex 变体,2026-07-23 已关停',
    sources: [
      { title: 'GPT-5.1-Codex Mini 模型文档', url: DOC('gpt-5.1-codex-mini') },
      DEPRECATIONS_PAGE,
    ],
    pricing: null,
    limits: ctx('400,000', '128,000'),
    trainingParams: null,
    matchAliases: ['gpt-5.1-codex-mini'],
    events: [
      { kind: 'api_available', occurredOn: '2025-11-13', title: 'gpt-5.1-codex 与 gpt-5.1-codex-mini 上线', sourceUrl: CL('2025-11-13') },
      { kind: 'deprecated', occurredOn: '2026-04-22', title: '弃用公告:2026-07-23 关停(替代 gpt-5.6-terra)', sourceUrl: DEPRECATIONS_PAGE.url },
      { kind: 'retired', occurredOn: '2026-07-23', title: '已从 API 关停', sourceUrl: DEPRECATIONS_PAGE.url },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-5.1-codex-max',
    name: 'GPT-5.1-Codex-Max',
    kind: 'text',
    stage: 'retired',
    availability: ['api'],
    summary: '面向长时任务的 GPT-5.1-Codex 变体,2026-07-23 已关停',
    sources: [
      { title: 'GPT-5.1-Codex-Max 模型文档', url: DOC('gpt-5.1-codex-max') },
      DEPRECATIONS_PAGE,
    ],
    pricing: null,
    limits: ctx('400,000', '128,000'),
    trainingParams: null,
    matchAliases: ['gpt-5.1-codex-max'],
    events: [
      { kind: 'api_available', occurredOn: '2025-12-04', title: 'gpt-5.1-codex-max 上线 Responses API', sourceUrl: CL('2025-12-04') },
      { kind: 'deprecated', occurredOn: '2026-04-22', title: '弃用公告:2026-07-23 关停(替代 gpt-5.6-sol)', sourceUrl: DEPRECATIONS_PAGE.url },
      { kind: 'retired', occurredOn: '2026-07-23', title: '已从 API 关停', sourceUrl: DEPRECATIONS_PAGE.url },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-5',
    name: 'GPT-5',
    kind: 'text',
    stage: 'deprecated',
    availability: ['api'],
    summary: '上一代推理旗舰:可配推理力度,编程与 agentic 长程任务;已宣布弃用',
    sources: [
      { title: 'GPT-5 模型文档', url: DOC('gpt-5') },
      PRICING_PAGE,
      DEPRECATIONS_PAGE,
    ],
    pricing: perM('1.25', '10.00'),
    limits: ctx('400,000', '128,000'),
    trainingParams: null,
    matchAliases: ['gpt-5'],
    events: [
      { kind: 'api_available', occurredOn: '2025-08-07', title: 'GPT-5 家族上线 API(gpt-5/mini/nano)', sourceUrl: CL('2025-08-07') },
      { kind: 'deprecated', occurredOn: '2026-06-11', title: '弃用公告:2026-12-11 关停(替代 gpt-5.6-sol)', sourceUrl: DEPRECATIONS_PAGE.url },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-5-mini',
    name: 'GPT-5 Mini',
    kind: 'text',
    stage: 'deprecated',
    availability: ['api'],
    summary: '近前沿智能的mini 档:成本敏感、低延迟、高吞吐;已宣布弃用',
    sources: [
      { title: 'GPT-5 Mini 模型文档', url: DOC('gpt-5-mini') },
      PRICING_PAGE,
      DEPRECATIONS_PAGE,
    ],
    pricing: perM('0.25', '2.00'),
    limits: ctx('400,000', '128,000'),
    trainingParams: null,
    matchAliases: ['gpt-5-mini'],
    events: [
      { kind: 'api_available', occurredOn: '2025-08-07', title: 'GPT-5 家族上线 API(gpt-5/mini/nano)', sourceUrl: CL('2025-08-07') },
      { kind: 'deprecated', occurredOn: '2026-06-11', title: '弃用公告:2026-12-11 关停(替代 gpt-5.6-terra)', sourceUrl: DEPRECATIONS_PAGE.url },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-5-nano',
    name: 'GPT-5 nano',
    kind: 'text',
    stage: 'deprecated',
    availability: ['api'],
    summary: 'GPT-5 家族最快最省档;已宣布弃用',
    sources: [
      { title: 'GPT-5 nano 模型文档', url: DOC('gpt-5-nano') },
      PRICING_PAGE,
      DEPRECATIONS_PAGE,
    ],
    pricing: perM('0.05', '0.40'),
    limits: ctx('400,000', '128,000'),
    trainingParams: null,
    matchAliases: ['gpt-5-nano'],
    events: [
      { kind: 'api_available', occurredOn: '2025-08-07', title: 'GPT-5 家族上线 API(gpt-5/mini/nano)', sourceUrl: CL('2025-08-07') },
      { kind: 'deprecated', occurredOn: '2026-06-11', title: '弃用公告:2026-12-11 关停(替代 gpt-5.6-luna)', sourceUrl: DEPRECATIONS_PAGE.url },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-5-pro',
    name: 'GPT-5 Pro',
    kind: 'text',
    stage: 'deprecated',
    availability: ['api'],
    summary: 'GPT-5 的 Pro 版本:更多算力深入思考;已宣布弃用',
    sources: [
      { title: 'GPT-5 Pro 模型文档', url: DOC('gpt-5-pro') },
      PRICING_PAGE,
      DEPRECATIONS_PAGE,
    ],
    pricing: perM('15.00', '120.00'),
    limits: ctx('400,000', '272,000'),
    trainingParams: null,
    matchAliases: ['gpt-5-pro'],
    events: [
      { kind: 'api_available', occurredOn: '2025-10-06', title: 'DevDay 发布:GPT-5 Pro 上线', sourceUrl: CL('2025-10-06') },
      { kind: 'deprecated', occurredOn: '2026-06-11', title: '弃用公告:2026-12-11 关停(替代 gpt-5.6-sol 的 pro 推理模式)', sourceUrl: DEPRECATIONS_PAGE.url },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-5-codex',
    name: 'GPT-5-Codex',
    kind: 'text',
    stage: 'retired',
    availability: ['api'],
    summary: 'GPT-5 的 Codex CLI 专用编程变体,2026-07-23 已关停',
    sources: [
      { title: 'GPT-5-Codex 模型文档', url: DOC('gpt-5-codex') },
      DEPRECATIONS_PAGE,
    ],
    pricing: null,
    limits: ctx('400,000', '128,000'),
    trainingParams: null,
    matchAliases: ['gpt-5-codex'],
    events: [
      { kind: 'api_available', occurredOn: '2025-09-23', title: 'gpt-5-codex 上线(Codex CLI 专用)', sourceUrl: CL('2025-09-23') },
      { kind: 'deprecated', occurredOn: '2026-04-22', title: '弃用公告:2026-07-23 关停(替代 gpt-5.6-sol)', sourceUrl: DEPRECATIONS_PAGE.url },
      { kind: 'retired', occurredOn: '2026-07-23', title: '已从 API 关停', sourceUrl: DEPRECATIONS_PAGE.url },
    ],
  },
  {
    provider: 'openai',
    officialId: 'codex-mini-latest',
    name: 'codex-mini-latest',
    kind: 'text',
    stage: 'retired',
    availability: ['api'],
    summary: 'Codex CLI 优化的快速推理模型,2026-02-12 已关停',
    sources: [
      { title: 'codex-mini-latest 模型文档', url: DOC('codex-mini-latest') },
      DEPRECATIONS_PAGE,
    ],
    pricing: null,
    limits: ctx('200,000', '100,000'),
    trainingParams: null,
    matchAliases: ['codex-mini-latest'],
    events: [
      { kind: 'api_available', occurredOn: '2025-05-15', title: 'codex-mini-latest 上线(Codex CLI 优化)', sourceUrl: CL('2025-05-15') },
      { kind: 'deprecated', occurredOn: '2025-11-17', title: '弃用公告:2026-02-12 关停(替代 gpt-5-codex-mini)', sourceUrl: DEPRECATIONS_PAGE.url },
      { kind: 'retired', occurredOn: '2026-02-12', title: '已从 API 关停', sourceUrl: DEPRECATIONS_PAGE.url },
    ],
  },
  {
    provider: 'openai',
    officialId: 'computer-use-preview',
    name: 'computer-use-preview',
    kind: 'text',
    stage: 'retired',
    availability: ['api'],
    summary: '计算机使用(computer use)工具专用模型,2026-07-23 已关停',
    sources: [
      { title: 'computer-use-preview 模型文档', url: DOC('computer-use-preview') },
      DEPRECATIONS_PAGE,
    ],
    pricing: null,
    limits: ctx('8,192', '1,024'),
    trainingParams: null,
    matchAliases: ['computer-use-preview'],
    events: [
      { kind: 'api_available', occurredOn: '2025-03-11', title: 'computer-use-preview 与搜索变体模型上线', sourceUrl: CL('2025-03-11') },
      { kind: 'deprecated', occurredOn: '2026-04-22', title: '弃用公告:2026-07-23 关停(替代 gpt-5.6-terra)', sourceUrl: DEPRECATIONS_PAGE.url },
      { kind: 'retired', occurredOn: '2026-07-23', title: '已从 API 关停', sourceUrl: DEPRECATIONS_PAGE.url },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-4.1',
    name: 'GPT-4.1',
    kind: 'text',
    stage: 'ga',
    availability: ['api'],
    summary: '最强非推理模型:指令遵循与编程强化,1M 上下文',
    sources: [
      { title: 'GPT-4.1 模型文档', url: DOC('gpt-4.1') },
      PRICING_PAGE,
      CHANGELOG_PAGE,
    ],
    pricing: perM('2.00', '8.00'),
    limits: ctx('1,047,576', '32,768'),
    trainingParams: null,
    matchAliases: ['gpt-4.1'],
    events: [
      { kind: 'api_available', occurredOn: '2025-04-14', title: 'GPT-4.1 家族上线(1M 上下文)', sourceUrl: CL('2025-04-14') },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-4.1-mini',
    name: 'GPT-4.1 Mini',
    kind: 'text',
    stage: 'ga',
    availability: ['api'],
    summary: 'GPT-4.1 的小型快速版',
    sources: [
      { title: 'GPT-4.1 Mini 模型文档', url: DOC('gpt-4.1-mini') },
      PRICING_PAGE,
      CHANGELOG_PAGE,
    ],
    pricing: perM('0.40', '1.60'),
    limits: ctx('1,047,576', '32,768'),
    trainingParams: null,
    matchAliases: ['gpt-4.1-mini'],
    events: [
      { kind: 'api_available', occurredOn: '2025-04-14', title: 'GPT-4.1 家族上线(1M 上下文)', sourceUrl: CL('2025-04-14') },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-4.1-nano',
    name: 'GPT-4.1 nano',
    kind: 'text',
    stage: 'deprecated',
    availability: ['api'],
    summary: 'GPT-4.1 最快最省档;已宣布弃用',
    sources: [
      { title: 'GPT-4.1 nano 模型文档', url: DOC('gpt-4.1-nano') },
      PRICING_PAGE,
      DEPRECATIONS_PAGE,
    ],
    pricing: perM('0.10', '0.40'),
    limits: ctx('1,047,576', '32,768'),
    trainingParams: null,
    matchAliases: ['gpt-4.1-nano'],
    events: [
      { kind: 'api_available', occurredOn: '2025-04-14', title: 'GPT-4.1 家族上线(1M 上下文)', sourceUrl: CL('2025-04-14') },
      { kind: 'deprecated', occurredOn: '2026-04-22', title: '弃用公告:2026-10-23 关停(替代 gpt-5.6-luna)', sourceUrl: DEPRECATIONS_PAGE.url },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-4o',
    name: 'GPT-4o',
    kind: 'text',
    stage: 'ga',
    availability: ['api'],
    summary: '快速、智能、灵活的多模态 GPT 模型(文本+图像输入)',
    sources: [
      { title: 'GPT-4o 模型文档', url: DOC('gpt-4o') },
      PRICING_PAGE,
      CHANGELOG_PAGE,
    ],
    pricing: perM('2.50', '10.00'),
    limits: ctx('128,000', '16,384'),
    trainingParams: null,
    matchAliases: ['gpt-4o'],
    events: [
      { kind: 'api_available', occurredOn: '2024-05-13', title: 'GPT-4o 上线 API(最快最可负担旗舰)', sourceUrl: CL('2024-05-13') },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-4o-mini',
    name: 'GPT-4o Mini',
    kind: 'text',
    stage: 'ga',
    availability: ['api'],
    summary: '快速、平价的小型模型,适合聚焦任务',
    sources: [
      { title: 'GPT-4o Mini 模型文档', url: DOC('gpt-4o-mini') },
      PRICING_PAGE,
      CHANGELOG_PAGE,
    ],
    pricing: perM('0.15', '0.60'),
    limits: ctx('128,000', '16,384'),
    trainingParams: null,
    matchAliases: ['gpt-4o-mini'],
    events: [
      { kind: 'api_available', occurredOn: '2024-07-18', title: 'GPT-4o mini 上线', sourceUrl: CL('2024-07-18') },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-4o-search-preview',
    name: 'GPT-4o Search Preview',
    kind: 'text',
    stage: 'retired',
    availability: ['api'],
    summary: '内置 web 搜索的 GPT-4o 变体(Chat Completions),2026-07-23 已关停',
    sources: [
      { title: 'GPT-4o Search Preview 模型文档', url: DOC('gpt-4o-search-preview') },
      DEPRECATIONS_PAGE,
    ],
    pricing: null,
    limits: ctx('128,000', '16,384'),
    trainingParams: null,
    matchAliases: ['gpt-4o-search-preview'],
    events: [
      { kind: 'api_available', occurredOn: '2025-03-11', title: 'gpt-4o-search-preview 上线(内置 web 搜索)', sourceUrl: CL('2025-03-11') },
      { kind: 'deprecated', occurredOn: '2026-04-22', title: '弃用公告:2026-07-23 关停(替代 gpt-5.6-terra)', sourceUrl: DEPRECATIONS_PAGE.url },
      { kind: 'retired', occurredOn: '2026-07-23', title: '已从 API 关停', sourceUrl: DEPRECATIONS_PAGE.url },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-4o-mini-search-preview',
    name: 'GPT-4o Mini Search Preview',
    kind: 'text',
    stage: 'retired',
    availability: ['api'],
    summary: '内置 web 搜索的 GPT-4o mini 变体,2026-07-23 已关停',
    sources: [
      { title: 'GPT-4o Mini Search Preview 模型文档', url: DOC('gpt-4o-mini-search-preview') },
      DEPRECATIONS_PAGE,
    ],
    pricing: null,
    limits: ctx('128,000', '16,384'),
    trainingParams: null,
    matchAliases: ['gpt-4o-mini-search-preview'],
    events: [
      { kind: 'api_available', occurredOn: '2025-03-11', title: 'gpt-4o-mini-search-preview 上线(内置 web 搜索)', sourceUrl: CL('2025-03-11') },
      { kind: 'deprecated', occurredOn: '2026-04-22', title: '弃用公告:2026-07-23 关停(替代 gpt-5.6-terra)', sourceUrl: DEPRECATIONS_PAGE.url },
      { kind: 'retired', occurredOn: '2026-07-23', title: '已从 API 关停', sourceUrl: DEPRECATIONS_PAGE.url },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-4.5-preview',
    name: 'GPT-4.5 Preview',
    kind: 'text',
    stage: 'retired',
    availability: ['api'],
    summary: '研究预览的旗舰大模型:高 EQ 与意图理解,长于创意与 agentic 规划;2025-07-14 已关停',
    sources: [
      { title: 'GPT-4.5 Preview 模型文档', url: DOC('gpt-4.5-preview') },
      DEPRECATIONS_PAGE,
    ],
    pricing: null,
    limits: ctx('128,000', '16,384'),
    trainingParams: null,
    matchAliases: ['gpt-4.5-preview', 'GPT-4.5'], // changelog 上线条目用展示名「GPT-4.5」
    events: [
      { kind: 'api_available', occurredOn: '2025-02-27', title: 'GPT-4.5 研究预览上线', sourceUrl: CL('2025-02-27') },
      { kind: 'deprecated', occurredOn: '2025-04-14', title: '弃用公告:2025-07-14 关停(替代 gpt-4.1)', sourceUrl: DEPRECATIONS_PAGE.url },
      { kind: 'retired', occurredOn: '2025-07-14', title: '已从 API 关停', sourceUrl: DEPRECATIONS_PAGE.url },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-4',
    name: 'GPT-4',
    kind: 'text',
    stage: 'deprecated',
    availability: ['api'],
    summary: '旧一代高智能 GPT 模型(8K 上下文);已宣布弃用',
    sources: [
      { title: 'GPT-4 模型文档', url: DOC('gpt-4') },
      PRICING_PAGE,
      DEPRECATIONS_PAGE,
    ],
    pricing: perM('30.00', '60.00'),
    limits: ctx('8,192', '8,192'),
    trainingParams: null,
    matchAliases: ['gpt-4'],
    events: [
      // 初始发布(2023-03)早于 changelog 覆盖,不回填上线事件
      { kind: 'deprecated', occurredOn: '2026-04-22', title: '弃用公告:2026-10-23 关停(替代 gpt-5.6-sol)', sourceUrl: DEPRECATIONS_PAGE.url },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-4-turbo',
    name: 'GPT-4 Turbo',
    kind: 'text',
    stage: 'deprecated',
    availability: ['api'],
    summary: '带视觉输入的旧一代高智能模型(128K);已宣布弃用',
    sources: [
      { title: 'GPT-4 Turbo 模型文档', url: DOC('gpt-4-turbo') },
      PRICING_PAGE,
      DEPRECATIONS_PAGE,
    ],
    pricing: perM('10.00', '30.00'),
    limits: ctx('128,000', '4,096'),
    trainingParams: null,
    matchAliases: ['gpt-4-turbo'],
    events: [
      { kind: 'api_available', occurredOn: '2024-04-09', title: 'GPT-4 Turbo with Vision 正式可用', sourceUrl: CL('2024-04-09') },
      { kind: 'deprecated', occurredOn: '2026-04-22', title: '弃用公告:2026-10-23 关停(替代 gpt-5.6-sol)', sourceUrl: DEPRECATIONS_PAGE.url },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-4-turbo-preview',
    name: 'GPT-4 Turbo Preview',
    kind: 'text',
    stage: 'retired',
    availability: ['api'],
    summary: '旧一代快速 GPT 预览模型;2026-03-26 已关停',
    sources: [
      { title: 'GPT-4 Turbo Preview 模型文档', url: DOC('gpt-4-turbo-preview') },
      DEPRECATIONS_PAGE,
    ],
    pricing: null,
    limits: ctx('128,000', '4,096'),
    trainingParams: null,
    matchAliases: ['gpt-4-turbo-preview', 'gpt-4-0125-preview'],
    events: [
      { kind: 'api_available', occurredOn: '2023-11-06', title: 'DevDay 发布:GPT-4 Turbo 预览版上线', sourceUrl: CL('2023-11-06') },
      { kind: 'deprecated', occurredOn: '2025-09-26', title: '弃用公告:2026-03-26 关停', sourceUrl: DEPRECATIONS_PAGE.url },
      { kind: 'retired', occurredOn: '2026-03-26', title: '已从 API 关停', sourceUrl: DEPRECATIONS_PAGE.url },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-3.5-turbo',
    name: 'GPT-3.5 Turbo',
    kind: 'text',
    stage: 'deprecated',
    availability: ['api'],
    summary: '旧一代平价 GPT 模型;已宣布弃用',
    sources: [
      { title: 'GPT-3.5 Turbo 模型文档', url: DOC('gpt-3.5-turbo') },
      PRICING_PAGE,
      DEPRECATIONS_PAGE,
    ],
    pricing: perM('0.50', '1.50'),
    limits: ctx('16,385', '4,096'),
    trainingParams: null,
    matchAliases: ['gpt-3.5-turbo'],
    events: [
      { kind: 'deprecated', occurredOn: '2026-04-22', title: '弃用公告:2026-10-23 关停(替代 gpt-5.6-terra)', sourceUrl: DEPRECATIONS_PAGE.url },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-3.5-turbo-instruct',
    name: 'gpt-3.5-turbo-instruct',
    kind: 'text',
    stage: 'deprecated',
    availability: ['api'],
    summary: 'completions 端点的 GPT-3.5 指令模型(遗留);已宣布弃用',
    sources: [
      { title: '弃用页(2025-09-26 公告)', url: DEPRECATIONS_PAGE.url },
      PRICING_PAGE,
    ],
    pricing: perM('1.50', '2.00'),
    limits: null,
    trainingParams: null,
    matchAliases: ['gpt-3.5-turbo-instruct'],
    events: [
      { kind: 'deprecated', occurredOn: '2025-09-26', title: '弃用公告:2026-09-28 关停(替代 gpt-5.6-terra)', sourceUrl: DEPRECATIONS_PAGE.url },
    ],
  },
  {
    provider: 'openai',
    officialId: 'babbage-002',
    name: 'babbage-002',
    kind: 'text',
    stage: 'deprecated',
    availability: ['api'],
    summary: 'GPT-3 ada/babbage 基座模型的替代基座(遗留);已宣布弃用',
    sources: [
      { title: 'babbage-002 模型文档', url: DOC('babbage-002') },
      PRICING_PAGE,
      DEPRECATIONS_PAGE,
    ],
    pricing: perM('0.40', '0.40'),
    limits: null,
    trainingParams: null,
    matchAliases: ['babbage-002'],
    events: [
      { kind: 'deprecated', occurredOn: '2025-09-26', title: '弃用公告:2026-09-28 关停(替代 gpt-5.6-terra)', sourceUrl: DEPRECATIONS_PAGE.url },
    ],
  },
  {
    provider: 'openai',
    officialId: 'davinci-002',
    name: 'davinci-002',
    kind: 'text',
    stage: 'deprecated',
    availability: ['api'],
    summary: 'GPT-3 curie/davinci 基座模型的替代基座(遗留);已宣布弃用',
    sources: [
      { title: 'davinci-002 模型文档', url: DOC('davinci-002') },
      PRICING_PAGE,
      DEPRECATIONS_PAGE,
    ],
    pricing: perM('2.00', '2.00'),
    limits: null,
    trainingParams: null,
    matchAliases: ['davinci-002'],
    events: [
      { kind: 'deprecated', occurredOn: '2025-09-26', title: '弃用公告:2026-09-28 关停(替代 gpt-5.6-terra)', sourceUrl: DEPRECATIONS_PAGE.url },
    ],
  },
  // ---- 文本(o 系列推理模型)----
  {
    provider: 'openai',
    officialId: 'o1',
    name: 'o1',
    kind: 'text',
    stage: 'deprecated',
    availability: ['api'],
    summary: '上一代全量 o 系列推理模型;已宣布弃用',
    sources: [
      { title: 'o1 模型文档', url: DOC('o1') },
      PRICING_PAGE,
      DEPRECATIONS_PAGE,
    ],
    pricing: perM('15.00', '60.00'),
    limits: ctx('200,000', '100,000'),
    trainingParams: null,
    matchAliases: ['o1'],
    events: [
      { kind: 'api_available', occurredOn: '2024-12-17', title: 'o1 正式上线 API(o1-preview 的全量版)', sourceUrl: CL('2024-12-17') },
      { kind: 'deprecated', occurredOn: '2026-04-22', title: '弃用公告:2026-10-23 关停(替代 gpt-5.6-sol)', sourceUrl: DEPRECATIONS_PAGE.url },
    ],
  },
  {
    provider: 'openai',
    officialId: 'o1-preview',
    name: 'o1 Preview',
    kind: 'text',
    stage: 'retired',
    availability: ['api'],
    summary: '首个 o 系列推理模型预览;2025-07-28 已关停',
    sources: [
      { title: 'o1 Preview 模型文档', url: DOC('o1-preview') },
      DEPRECATIONS_PAGE,
    ],
    pricing: null,
    limits: ctx('128,000', '32,768'),
    trainingParams: null,
    matchAliases: ['o1-preview'],
    events: [
      { kind: 'api_available', occurredOn: '2024-09-12', title: 'o1-preview 与 o1-mini 上线(强化学习推理)', sourceUrl: CL('2024-09-12') },
      { kind: 'deprecated', occurredOn: '2025-04-28', title: '弃用公告:2025-07-28 关停(替代 o3)', sourceUrl: DEPRECATIONS_PAGE.url },
      { kind: 'retired', occurredOn: '2025-07-28', title: '已从 API 关停', sourceUrl: DEPRECATIONS_PAGE.url },
    ],
  },
  {
    provider: 'openai',
    officialId: 'o1-mini',
    name: 'o1-mini',
    kind: 'text',
    stage: 'retired',
    availability: ['api'],
    summary: 'o1 的小型替代;2025-10-27 已关停',
    sources: [
      { title: 'o1-mini 模型文档', url: DOC('o1-mini') },
      DEPRECATIONS_PAGE,
    ],
    pricing: null,
    limits: ctx('128,000', '65,536'),
    trainingParams: null,
    matchAliases: ['o1-mini'],
    events: [
      { kind: 'api_available', occurredOn: '2024-09-12', title: 'o1-preview 与 o1-mini 上线(强化学习推理)', sourceUrl: CL('2024-09-12') },
      { kind: 'deprecated', occurredOn: '2025-04-28', title: '弃用公告:2025-10-27 关停(替代 o4-mini)', sourceUrl: DEPRECATIONS_PAGE.url },
      { kind: 'retired', occurredOn: '2025-10-27', title: '已从 API 关停', sourceUrl: DEPRECATIONS_PAGE.url },
    ],
  },
  {
    provider: 'openai',
    officialId: 'o1-pro',
    name: 'o1-pro',
    kind: 'text',
    stage: 'deprecated',
    availability: ['api'],
    summary: 'o1 的 Pro 版本:更多算力换取更好推理;已宣布弃用',
    sources: [
      { title: 'o1-pro 模型文档', url: DOC('o1-pro') },
      PRICING_PAGE,
      DEPRECATIONS_PAGE,
    ],
    pricing: perM('150.00', '600.00'),
    limits: ctx('200,000', '100,000'),
    trainingParams: null,
    matchAliases: ['o1-pro'],
    events: [
      { kind: 'api_available', occurredOn: '2025-03-19', title: 'o1-pro 上线', sourceUrl: CL('2025-03-19') },
      { kind: 'deprecated', occurredOn: '2026-04-22', title: '弃用公告:2026-10-23 关停(替代 gpt-5.6-sol 的 pro 推理模式)', sourceUrl: DEPRECATIONS_PAGE.url },
    ],
  },
  {
    provider: 'openai',
    officialId: 'o3',
    name: 'o3',
    kind: 'text',
    stage: 'deprecated',
    availability: ['api'],
    summary: '复杂任务推理模型(数学/科学/编程/视觉推理);已宣布弃用',
    sources: [
      { title: 'o3 模型文档', url: DOC('o3') },
      PRICING_PAGE,
      DEPRECATIONS_PAGE,
    ],
    pricing: perM('2.00', '8.00'),
    limits: ctx('200,000', '100,000'),
    trainingParams: null,
    matchAliases: ['o3'],
    events: [
      { kind: 'api_available', occurredOn: '2025-04-16', title: 'o3 与 o4-mini 上线', sourceUrl: CL('2025-04-16') },
      { kind: 'deprecated', occurredOn: '2026-06-11', title: '弃用公告:2026-12-11 关停(替代 gpt-5.6-sol)', sourceUrl: DEPRECATIONS_PAGE.url },
    ],
  },
  {
    provider: 'openai',
    officialId: 'o3-mini',
    name: 'o3-mini',
    kind: 'text',
    stage: 'deprecated',
    availability: ['api'],
    summary: '科学/数学/编程优化的小型推理模型;已宣布弃用',
    sources: [
      { title: 'o3-mini 模型文档', url: DOC('o3-mini') },
      PRICING_PAGE,
      DEPRECATIONS_PAGE,
    ],
    pricing: perM('1.10', '4.40'),
    limits: ctx('200,000', '100,000'),
    trainingParams: null,
    matchAliases: ['o3-mini'],
    events: [
      { kind: 'api_available', occurredOn: '2025-01-31', title: 'o3-mini 上线', sourceUrl: CL('2025-01-31') },
      { kind: 'deprecated', occurredOn: '2026-04-22', title: '弃用公告:2026-10-23 关停(替代 gpt-5.6-sol)', sourceUrl: DEPRECATIONS_PAGE.url },
    ],
  },
  {
    provider: 'openai',
    officialId: 'o3-pro',
    name: 'o3-pro',
    kind: 'text',
    stage: 'deprecated',
    availability: ['api'],
    summary: 'o3 的 Pro 版本:更多算力;已宣布弃用',
    sources: [
      { title: 'o3-pro 模型文档', url: DOC('o3-pro') },
      PRICING_PAGE,
      DEPRECATIONS_PAGE,
    ],
    pricing: perM('20.00', '80.00'),
    limits: ctx('200,000', '100,000'),
    trainingParams: null,
    matchAliases: ['o3-pro'],
    events: [
      { kind: 'api_available', occurredOn: '2025-06-10', title: 'o3-pro 上线(o3 同步降价)', sourceUrl: CL('2025-06-10') },
      { kind: 'deprecated', occurredOn: '2026-06-11', title: '弃用公告:2026-12-11 关停(替代 gpt-5.6-sol 的 pro 推理模式)', sourceUrl: DEPRECATIONS_PAGE.url },
    ],
  },
  {
    provider: 'openai',
    officialId: 'o3-deep-research',
    name: 'o3-deep-research',
    kind: 'text',
    stage: 'retired',
    availability: ['api'],
    summary: 'o 系列深度研究变体:深度分析与研究任务;2026-07-23 已关停',
    sources: [
      { title: 'o3-deep-research 模型文档', url: DOC('o3-deep-research') },
      DEPRECATIONS_PAGE,
    ],
    pricing: null,
    limits: ctx('200,000', '100,000'),
    trainingParams: null,
    matchAliases: ['o3-deep-research'],
    events: [
      { kind: 'api_available', occurredOn: '2025-06-26', title: 'o3-deep-research 与 o4-mini-deep-research 上线', sourceUrl: CL('2025-06-26') },
      { kind: 'deprecated', occurredOn: '2026-04-22', title: '弃用公告:2026-07-23 关停(替代 gpt-5.6-sol)', sourceUrl: DEPRECATIONS_PAGE.url },
      { kind: 'retired', occurredOn: '2026-07-23', title: '已从 API 关停', sourceUrl: DEPRECATIONS_PAGE.url },
    ],
  },
  {
    provider: 'openai',
    officialId: 'o4-mini',
    name: 'o4-mini',
    kind: 'text',
    stage: 'deprecated',
    availability: ['api'],
    summary: '快速、省成本的推理模型;已宣布弃用',
    sources: [
      { title: 'o4-mini 模型文档', url: DOC('o4-mini') },
      PRICING_PAGE,
      DEPRECATIONS_PAGE,
    ],
    pricing: perM('1.10', '4.40'),
    limits: ctx('200,000', '100,000'),
    trainingParams: null,
    matchAliases: ['o4-mini'],
    events: [
      { kind: 'api_available', occurredOn: '2025-04-16', title: 'o3 与 o4-mini 上线', sourceUrl: CL('2025-04-16') },
      { kind: 'deprecated', occurredOn: '2026-04-22', title: '弃用公告:2026-10-23 关停(替代 gpt-5.6-terra)', sourceUrl: DEPRECATIONS_PAGE.url },
    ],
  },
  {
    provider: 'openai',
    officialId: 'o4-mini-deep-research',
    name: 'o4-mini-deep-research',
    kind: 'text',
    stage: 'retired',
    availability: ['api'],
    summary: '更快更省的深度研究变体;2026-07-23 已关停',
    sources: [
      { title: 'o4-mini-deep-research 模型文档', url: DOC('o4-mini-deep-research') },
      DEPRECATIONS_PAGE,
    ],
    pricing: null,
    limits: ctx('200,000', '100,000'),
    trainingParams: null,
    matchAliases: ['o4-mini-deep-research'],
    events: [
      { kind: 'api_available', occurredOn: '2025-06-26', title: 'o3-deep-research 与 o4-mini-deep-research 上线', sourceUrl: CL('2025-06-26') },
      { kind: 'deprecated', occurredOn: '2026-04-22', title: '弃用公告:2026-07-23 关停(替代 gpt-5.6-sol)', sourceUrl: DEPRECATIONS_PAGE.url },
      { kind: 'retired', occurredOn: '2026-07-23', title: '已从 API 关停', sourceUrl: DEPRECATIONS_PAGE.url },
    ],
  },
  // ---- 文本(开放权重 gpt-oss 家族)----
  {
    provider: 'openai',
    officialId: 'gpt-oss-120b',
    name: 'gpt-oss-120b',
    kind: 'text',
    stage: 'ga',
    availability: ['api', 'open_weights'],
    summary: '最强开放权重模型:单张 H100 即可部署,harmony 响应格式',
    sources: [
      { title: 'gpt-oss-120b 模型文档', url: DOC('gpt-oss-120b') },
      HF('gpt-oss-120b'),
    ],
    pricing: null, // 官方价格页未单列(API 计价随Responses 端点)
    limits: ctx('131,072', '131,072'),
    trainingParams: { total: '117B', active: '5.1B' }, // 官方 README「117B parameters with 5.1B active」
    matchAliases: ['gpt-oss-120b'],
    events: [
      // 两渠道同日但按事件分立(权重开放 / API 上线,issues/03 AC「按事件分别保留」)
      { kind: 'weights_available', occurredOn: '2025-08-05', title: 'gpt-oss 开放权重发布(120b/20b)', sourceUrl: HF('gpt-oss-120b').url },
      { kind: 'api_available', occurredOn: '2025-08-05', title: 'gpt-oss 经 OpenAI API 提供(Responses 端点)', sourceUrl: DOC('gpt-oss-120b') },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-oss-20b',
    name: 'gpt-oss-20b',
    kind: 'text',
    stage: 'ga',
    availability: ['api', 'open_weights'],
    summary: '中型开放权重模型:低延迟,适合本地或专用场景',
    sources: [
      { title: 'gpt-oss-20b 模型文档', url: DOC('gpt-oss-20b') },
      HF('gpt-oss-20b'),
    ],
    pricing: null,
    limits: ctx('131,072', '131,072'),
    trainingParams: { total: '21B', active: '3.6B' },
    matchAliases: ['gpt-oss-20b'],
    events: [
      // 两渠道同日但按事件分立(权重开放 / API 上线,issues/03 AC「按事件分别保留」)
      { kind: 'weights_available', occurredOn: '2025-08-05', title: 'gpt-oss 开放权重发布(120b/20b)', sourceUrl: HF('gpt-oss-20b').url },
      { kind: 'api_available', occurredOn: '2025-08-05', title: 'gpt-oss 经 OpenAI API 提供(Responses 端点)', sourceUrl: DOC('gpt-oss-20b') },
    ],
  },
  // ---- 审核/分类(开放权重安全模型;不在 API 目录,changelog 记录)----
  {
    provider: 'openai',
    officialId: 'gpt-oss-safeguard-120b',
    name: 'gpt-oss-safeguard-120b',
    kind: 'moderation_classification',
    stage: 'ga',
    availability: ['open_weights'],
    summary: '基于 gpt-oss 的安全推理模型:守护 agentic 系统的输入输出安全',
    sources: [
      { title: 'HuggingFace 官方 gpt-oss-safeguard 合集', url: 'https://huggingface.co/collections/openai/gpt-oss-safeguard' },
      CHANGELOG_PAGE,
    ],
    pricing: null, // 仅开放权重,无 API 计价
    limits: null,
    trainingParams: null,
    matchAliases: ['gpt-oss-safeguard-120b'],
    events: [
      { kind: 'weights_available', occurredOn: '2025-10-29', title: 'gpt-oss-safeguard-120b/20b 开放权重发布', sourceUrl: 'https://huggingface.co/collections/openai/gpt-oss-safeguard' },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-oss-safeguard-20b',
    name: 'gpt-oss-safeguard-20b',
    kind: 'moderation_classification',
    stage: 'ga',
    availability: ['open_weights'],
    summary: 'gpt-oss-safeguard 的小型档:低延迟安全推理',
    sources: [
      { title: 'HuggingFace 官方 gpt-oss-safeguard 合集', url: 'https://huggingface.co/collections/openai/gpt-oss-safeguard' },
      CHANGELOG_PAGE,
    ],
    pricing: null,
    limits: null,
    trainingParams: null,
    matchAliases: ['gpt-oss-safeguard-20b'],
    events: [
      { kind: 'weights_available', occurredOn: '2025-10-29', title: 'gpt-oss-safeguard-120b/20b 开放权重发布', sourceUrl: 'https://huggingface.co/collections/openai/gpt-oss-safeguard' },
    ],
  },
  // ---- 音频/语音(Realtime 家族)----
  {
    provider: 'openai',
    officialId: 'gpt-realtime-2.1',
    name: 'GPT-Realtime-2.1',
    kind: 'audio_speech',
    stage: 'ga',
    availability: ['api'],
    summary: '实时语音推理模型:字母数字识别、静默与噪声处理、打断行为改进',
    sources: [
      { title: 'GPT-Realtime-2.1 模型文档', url: DOC('gpt-realtime-2.1') },
      PRICING_PAGE,
      CHANGELOG_PAGE,
    ],
    pricing: perModality(
      ['音频', '输入 $32/百万 tokens · 输出 $64/百万 tokens'],
      ['文本', '输入 $4/百万 tokens · 输出 $24/百万 tokens'],
      ['图像输入', '$5/百万 tokens'],
    ),
    limits: ctx('128,000', '32,000'),
    trainingParams: null,
    matchAliases: ['gpt-realtime-2.1'],
    events: [
      { kind: 'api_available', occurredOn: '2026-07-06', title: 'GPT-Realtime-2.1 与 mini 上线', sourceUrl: CL('2026-07-06') },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-realtime-2.1-mini',
    name: 'GPT-Realtime-2.1 Mini',
    kind: 'audio_speech',
    stage: 'ga',
    availability: ['api'],
    summary: '更快更省的实时语音蒸馏推理模型',
    sources: [
      { title: 'GPT-Realtime-2.1 Mini 模型文档', url: DOC('gpt-realtime-2.1-mini') },
      PRICING_PAGE,
      CHANGELOG_PAGE,
    ],
    pricing: perModality(
      ['音频', '输入 $10/百万 tokens · 输出 $20/百万 tokens'],
      ['文本', '输入 $0.60/百万 tokens · 输出 $2.40/百万 tokens'],
      ['图像输入', '$0.80/百万 tokens'],
    ),
    limits: ctx('128,000', '32,000'),
    trainingParams: null,
    matchAliases: ['gpt-realtime-2.1-mini'],
    events: [
      { kind: 'api_available', occurredOn: '2026-07-06', title: 'GPT-Realtime-2.1 与 mini 上线', sourceUrl: CL('2026-07-06') },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-realtime-2',
    name: 'GPT-Realtime-2',
    kind: 'audio_speech',
    stage: 'ga',
    availability: ['api'],
    summary: '可配推理的实时语音模型:面向 speech-to-speech 代理',
    sources: [
      { title: 'GPT-Realtime-2 模型文档', url: DOC('gpt-realtime-2') },
      PRICING_PAGE,
      CHANGELOG_PAGE,
    ],
    pricing: perModality(
      ['音频', '输入 $32/百万 tokens · 输出 $64/百万 tokens'],
      ['文本', '输入 $4/百万 tokens · 输出 $24/百万 tokens'],
      ['图像输入', '$5/百万 tokens'],
    ),
    limits: ctx('128,000', '32,000'),
    trainingParams: null,
    matchAliases: ['gpt-realtime-2'],
    events: [
      { kind: 'api_available', occurredOn: '2026-05-07', title: 'GPT-Realtime-2 / Translate / Whisper 上线', sourceUrl: CL('2026-05-07') },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-realtime-translate',
    name: 'GPT-Realtime-Translate',
    kind: 'audio_speech',
    stage: 'ga',
    availability: ['api'],
    summary: '流式语音到语音翻译模型',
    sources: [
      { title: 'GPT-Realtime-Translate 模型文档', url: DOC('gpt-realtime-translate') },
      PRICING_PAGE,
      CHANGELOG_PAGE,
    ],
    pricing: price([{ text: '$0.034/分钟', scope: '实时翻译' }]),
    limits: ctx('16,000', '2,000'),
    trainingParams: null,
    matchAliases: ['gpt-realtime-translate'],
    events: [
      { kind: 'api_available', occurredOn: '2026-05-07', title: 'GPT-Realtime-2 / Translate / Whisper 上线', sourceUrl: CL('2026-05-07') },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-realtime-whisper',
    name: 'GPT-Realtime-Whisper',
    kind: 'audio_speech',
    stage: 'ga',
    availability: ['api'],
    summary: '流式语音转文字模型:实时转录',
    sources: [
      { title: 'GPT-Realtime-Whisper 模型文档', url: DOC('gpt-realtime-whisper') },
      PRICING_PAGE,
      CHANGELOG_PAGE,
    ],
    pricing: price([{ text: '$0.017/分钟', scope: '实时转录' }]),
    limits: ctx('16,000', '2,000'),
    trainingParams: null,
    matchAliases: ['gpt-realtime-whisper'],
    events: [
      { kind: 'api_available', occurredOn: '2026-05-07', title: 'GPT-Realtime-2 / Translate / Whisper 上线', sourceUrl: CL('2026-05-07') },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-realtime-1.5',
    name: 'GPT-Realtime-1.5',
    kind: 'audio_speech',
    stage: 'ga',
    availability: ['api'],
    summary: '上一代最佳语音模型:音频进音频出(Realtime API)',
    sources: [
      { title: 'GPT-Realtime-1.5 模型文档', url: DOC('gpt-realtime-1.5') },
      PRICING_PAGE,
      CHANGELOG_PAGE,
    ],
    pricing: perModality(
      ['音频', '输入 $32/百万 tokens · 输出 $64/百万 tokens'],
      ['文本', '输入 $4/百万 tokens · 输出 $16/百万 tokens'],
      ['图像输入', '$5/百万 tokens'],
    ),
    limits: ctx('32,000', '4,096'),
    trainingParams: null,
    matchAliases: ['gpt-realtime-1.5'],
    events: [
      { kind: 'api_available', occurredOn: '2026-02-23', title: 'GPT-Realtime-1.5 与 GPT-Audio-1.5 上线', sourceUrl: CL('2026-02-23') },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-realtime',
    name: 'GPT-Realtime',
    kind: 'audio_speech',
    stage: 'deprecated',
    availability: ['api'],
    summary: 'GA 首代 Realtime 模型(文本/音频/图像输入输出);已宣布弃用',
    sources: [
      { title: 'GPT-Realtime 模型文档', url: DOC('gpt-realtime') },
      PRICING_PAGE,
      DEPRECATIONS_PAGE,
    ],
    pricing: perModality(
      ['音频', '输入 $32/百万 tokens · 输出 $64/百万 tokens'],
      ['文本', '输入 $4/百万 tokens · 输出 $16/百万 tokens'],
      ['图像输入', '$5/百万 tokens'],
    ),
    limits: ctx('32,000', '4,096'),
    trainingParams: null,
    matchAliases: ['gpt-realtime'],
    events: [
      { kind: 'api_available', occurredOn: '2025-08-28', title: 'Realtime API 正式版上线(gpt-realtime / gpt-audio)', sourceUrl: CL('2025-08-28') },
      { kind: 'deprecated', occurredOn: '2026-07-20', title: '弃用公告:2027-01-20 关停(替代 gpt-realtime-2.1)', sourceUrl: DEPRECATIONS_PAGE.url },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-realtime-mini',
    name: 'GPT-Realtime Mini',
    kind: 'audio_speech',
    stage: 'deprecated',
    availability: ['api'],
    summary: '成本优化的 Realtime 蒸馏模型;已宣布弃用',
    sources: [
      { title: 'GPT-Realtime Mini 模型文档', url: DOC('gpt-realtime-mini') },
      PRICING_PAGE,
      DEPRECATIONS_PAGE,
    ],
    pricing: perModality(
      ['音频', '输入 $10/百万 tokens · 输出 $20/百万 tokens'],
      ['文本', '输入 $0.60/百万 tokens · 输出 $2.40/百万 tokens'],
      ['图像输入', '$0.80/百万 tokens'],
    ),
    limits: ctx('32,000', '4,096'),
    trainingParams: null,
    matchAliases: ['gpt-realtime-mini'],
    events: [
      { kind: 'api_available', occurredOn: '2025-10-06', title: 'DevDay 发布:GPT-Realtime mini 上线', sourceUrl: CL('2025-10-06') },
      { kind: 'deprecated', occurredOn: '2026-07-20', title: '弃用公告:2027-01-20 关停(替代 gpt-realtime-2.1-mini)', sourceUrl: DEPRECATIONS_PAGE.url },
    ],
  },
  // ---- 音频/语音(Chat Completions 音频家族)----
  {
    provider: 'openai',
    officialId: 'gpt-audio-1.5',
    name: 'GPT-Audio-1.5',
    kind: 'audio_speech',
    stage: 'ga',
    availability: ['api'],
    summary: '最佳语音模型:音频进音频出(Chat Completions)',
    sources: [
      { title: 'GPT-Audio-1.5 模型文档', url: DOC('gpt-audio-1.5') },
      PRICING_PAGE,
      CHANGELOG_PAGE,
    ],
    pricing: perModality(
      ['音频', '输入 $32/百万 tokens · 输出 $64/百万 tokens'],
      ['文本', '输入 $2.50/百万 tokens · 输出 $10/百万 tokens'],
    ),
    limits: ctx('128,000', '16,384'),
    trainingParams: null,
    matchAliases: ['gpt-audio-1.5'],
    events: [
      { kind: 'api_available', occurredOn: '2026-02-23', title: 'GPT-Realtime-1.5 与 GPT-Audio-1.5 上线', sourceUrl: CL('2026-02-23') },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-audio',
    name: 'GPT-Audio',
    kind: 'audio_speech',
    stage: 'deprecated',
    availability: ['api'],
    summary: 'Chat Completions 的音频输入输出模型(4o-audio 系列后继);已宣布弃用',
    sources: [
      { title: 'GPT-Audio 模型文档', url: DOC('gpt-audio') },
      PRICING_PAGE,
      DEPRECATIONS_PAGE,
    ],
    pricing: perModality(
      ['音频', '输入 $32/百万 tokens · 输出 $64/百万 tokens'],
      ['文本', '输入 $2.50/百万 tokens · 输出 $10/百万 tokens'],
    ),
    limits: ctx('128,000', '16,384'),
    trainingParams: null,
    matchAliases: ['gpt-audio'],
    events: [
      { kind: 'api_available', occurredOn: '2025-08-28', title: 'Realtime API 正式版上线(gpt-realtime / gpt-audio)', sourceUrl: CL('2025-08-28') },
      { kind: 'deprecated', occurredOn: '2026-07-20', title: '弃用公告:2027-01-20 关停(替代 gpt-audio-1.5)', sourceUrl: DEPRECATIONS_PAGE.url },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-audio-mini',
    name: 'GPT-Audio Mini',
    kind: 'audio_speech',
    stage: 'deprecated',
    availability: ['api'],
    summary: '成本优化的音频模型;已宣布弃用',
    sources: [
      { title: 'GPT-Audio Mini 模型文档', url: DOC('gpt-audio-mini') },
      PRICING_PAGE,
      DEPRECATIONS_PAGE,
    ],
    pricing: perModality(
      ['音频', '输入 $10/百万 tokens · 输出 $20/百万 tokens'],
      ['文本', '输入 $0.60/百万 tokens · 输出 $2.40/百万 tokens'],
    ),
    limits: ctx('128,000', '16,384'),
    trainingParams: null,
    matchAliases: ['gpt-audio-mini'],
    events: [
      { kind: 'api_available', occurredOn: '2025-10-06', title: 'DevDay 发布:gpt-audio-mini 上线', sourceUrl: CL('2025-10-06') },
      { kind: 'deprecated', occurredOn: '2026-07-20', title: '弃用公告:2027-01-20 关停(替代 gpt-audio-1.5)', sourceUrl: DEPRECATIONS_PAGE.url },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-4o-realtime-preview',
    name: 'GPT-4o Realtime',
    kind: 'audio_speech',
    stage: 'retired',
    availability: ['api'],
    summary: '4o 时代的实时文本/音频模型(预览);2026-05-07 已关停',
    sources: [
      { title: 'GPT-4o Realtime 模型文档', url: DOC('gpt-4o-realtime-preview') },
      DEPRECATIONS_PAGE,
    ],
    pricing: null,
    limits: ctx('32,000', '4,096'),
    trainingParams: null,
    matchAliases: ['gpt-4o-realtime-preview'],
    events: [
      { kind: 'api_available', occurredOn: '2024-10-01', title: 'DevDay 发布:Realtime API 预览(gpt-4o-realtime-preview)', sourceUrl: CL('2024-10-01') },
      { kind: 'deprecated', occurredOn: '2025-09-15', title: '弃用公告:2026-05-07 关停(替代 gpt-realtime-1.5)', sourceUrl: DEPRECATIONS_PAGE.url },
      { kind: 'retired', occurredOn: '2026-05-07', title: '已从 API 关停', sourceUrl: DEPRECATIONS_PAGE.url },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-4o-mini-realtime-preview',
    name: 'GPT-4o Mini Realtime',
    kind: 'audio_speech',
    stage: 'retired',
    availability: ['api'],
    summary: '4o mini 实时模型(预览);2026-05-07 已关停',
    sources: [
      { title: 'GPT-4o Mini Realtime 模型文档', url: DOC('gpt-4o-mini-realtime-preview') },
      DEPRECATIONS_PAGE,
    ],
    pricing: null,
    limits: ctx('16,000', '4,096'),
    trainingParams: null,
    matchAliases: ['gpt-4o-mini-realtime-preview'],
    events: [
      { kind: 'api_available', occurredOn: '2024-12-17', title: 'gpt-4o-mini-realtime-preview 上线(默认快照口径)', sourceUrl: DOC('gpt-4o-mini-realtime-preview') },
      { kind: 'deprecated', occurredOn: '2025-09-15', title: '弃用公告:2026-05-07 关停(替代 gpt-realtime-mini)', sourceUrl: DEPRECATIONS_PAGE.url },
      { kind: 'retired', occurredOn: '2026-05-07', title: '已从 API 关停', sourceUrl: DEPRECATIONS_PAGE.url },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-4o-audio-preview',
    name: 'GPT-4o Audio',
    kind: 'audio_speech',
    stage: 'retired',
    availability: ['api'],
    summary: '4o 音频输入输出模型(Chat Completions);2026-05-07 已关停',
    sources: [
      { title: 'GPT-4o Audio 模型文档', url: DOC('gpt-4o-audio-preview') },
      DEPRECATIONS_PAGE,
    ],
    pricing: null,
    limits: ctx('128,000', '16,384'),
    trainingParams: null,
    matchAliases: ['gpt-4o-audio-preview'],
    events: [
      { kind: 'api_available', occurredOn: '2024-10-17', title: 'gpt-4o-audio-preview 上线(Chat Completions 音频)', sourceUrl: CL('2024-10-17') },
      { kind: 'deprecated', occurredOn: '2025-09-15', title: '弃用公告:2026-05-07 关停(替代 gpt-audio-1.5)', sourceUrl: DEPRECATIONS_PAGE.url },
      { kind: 'retired', occurredOn: '2026-05-07', title: '已从 API 关停', sourceUrl: DEPRECATIONS_PAGE.url },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-4o-mini-audio-preview',
    name: 'GPT-4o Mini Audio',
    kind: 'audio_speech',
    stage: 'retired',
    availability: ['api'],
    summary: '4o mini 音频输入输出模型;2026-05-07 已关停',
    sources: [
      { title: 'GPT-4o Mini Audio 模型文档', url: DOC('gpt-4o-mini-audio-preview') },
      DEPRECATIONS_PAGE,
    ],
    pricing: null,
    limits: ctx('128,000', '16,384'),
    trainingParams: null,
    matchAliases: ['gpt-4o-mini-audio-preview'],
    events: [
      { kind: 'api_available', occurredOn: '2024-12-17', title: 'gpt-4o-mini-audio-preview 上线(默认快照口径)', sourceUrl: DOC('gpt-4o-mini-audio-preview') },
      { kind: 'deprecated', occurredOn: '2025-09-15', title: '弃用公告:2026-05-07 关停(替代 gpt-audio-mini)', sourceUrl: DEPRECATIONS_PAGE.url },
      { kind: 'retired', occurredOn: '2026-05-07', title: '已从 API 关停', sourceUrl: DEPRECATIONS_PAGE.url },
    ],
  },
  // ---- 音频/语音(转录与合成)----
  {
    provider: 'openai',
    officialId: 'gpt-transcribe',
    name: 'GPT-Transcribe',
    kind: 'audio_speech',
    stage: 'ga',
    availability: ['api'],
    summary: '高精度语音转文字:文件转录与 Realtime 已提交轮次的终稿转录',
    sources: [
      { title: 'GPT-Transcribe 模型文档', url: DOC('gpt-transcribe') },
      PRICING_PAGE,
      CHANGELOG_PAGE,
    ],
    pricing: price([{ text: '$0.0045/分钟', scope: null }]),
    limits: null,
    trainingParams: null,
    matchAliases: ['gpt-transcribe'],
    events: [
      { kind: 'api_available', occurredOn: '2026-07-28', title: 'GPT Transcribe 与 GPT Live Transcribe 发布', sourceUrl: CL('2026-07-28') },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-live-transcribe',
    name: 'GPT-Live-Transcribe',
    kind: 'audio_speech',
    stage: 'ga',
    availability: ['api'],
    summary: '低延迟流式语音转文字:实时转录',
    sources: [
      { title: 'GPT-Live-Transcribe 模型文档', url: DOC('gpt-live-transcribe') },
      PRICING_PAGE,
      CHANGELOG_PAGE,
    ],
    pricing: price([{ text: '$0.017/分钟', scope: '实时转录' }]),
    limits: null,
    trainingParams: null,
    matchAliases: ['gpt-live-transcribe'],
    events: [
      { kind: 'api_available', occurredOn: '2026-07-28', title: 'GPT Transcribe 与 GPT Live Transcribe 发布', sourceUrl: CL('2026-07-28') },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-4o-transcribe',
    name: 'GPT-4o Transcribe',
    kind: 'audio_speech',
    stage: 'ga',
    availability: ['api'],
    summary: '4o 驱动的语音转文字模型',
    sources: [
      { title: 'GPT-4o Transcribe 模型文档', url: DOC('gpt-4o-transcribe') },
      PRICING_PAGE,
      CHANGELOG_PAGE,
    ],
    pricing: perModality(
      ['token 计价', '输入 $2.50/百万 tokens · 输出 $10/百万 tokens'],
      ['折合', '约 $0.006/分钟'],
    ),
    limits: ctx('16,000', '2,000'),
    trainingParams: null,
    matchAliases: ['gpt-4o-transcribe'],
    events: [
      { kind: 'api_available', occurredOn: '2025-03-20', title: 'Audio API 扩充:4o-transcribe / mini-transcribe / mini-tts 上线', sourceUrl: CL('2025-03-20') },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-4o-mini-transcribe',
    name: 'GPT-4o Mini Transcribe',
    kind: 'audio_speech',
    stage: 'ga',
    availability: ['api'],
    summary: '4o mini 驱动的语音转文字模型(官方推荐优于 4o-transcribe)',
    sources: [
      { title: 'GPT-4o Mini Transcribe 模型文档', url: DOC('gpt-4o-mini-transcribe') },
      PRICING_PAGE,
      CHANGELOG_PAGE,
    ],
    pricing: perModality(
      ['token 计价', '输入 $1.25/百万 tokens · 输出 $5/百万 tokens'],
      ['折合', '约 $0.003/分钟'],
    ),
    limits: ctx('16,000', '2,000'),
    trainingParams: null,
    matchAliases: ['gpt-4o-mini-transcribe'],
    events: [
      { kind: 'api_available', occurredOn: '2025-03-20', title: 'Audio API 扩充:4o-transcribe / mini-transcribe / mini-tts 上线', sourceUrl: CL('2025-03-20') },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-4o-transcribe-diarize',
    name: 'GPT-4o Transcribe Diarize',
    kind: 'audio_speech',
    stage: 'ga',
    availability: ['api'],
    summary: '带说话人分离(diarization)的 4o 转录模型',
    sources: [
      { title: 'GPT-4o Transcribe Diarize 模型文档', url: DOC('gpt-4o-transcribe-diarize') },
      PRICING_PAGE,
    ],
    pricing: perModality(
      ['token 计价', '输入 $2.50/百万 tokens · 输出 $10/百万 tokens'],
      ['折合', '约 $0.006/分钟'],
    ),
    limits: ctx('16,000', '2,000'),
    trainingParams: null,
    matchAliases: ['gpt-4o-transcribe-diarize'],
    events: [],
  },
  {
    provider: 'openai',
    officialId: 'gpt-4o-mini-tts',
    name: 'GPT-4o Mini TTS',
    kind: 'audio_speech',
    stage: 'ga',
    availability: ['api'],
    summary: '4o mini 驱动的语音合成模型(可配音色与指令)',
    sources: [
      { title: 'GPT-4o Mini TTS 模型文档', url: DOC('gpt-4o-mini-tts') },
      PRICING_PAGE,
      CHANGELOG_PAGE,
    ],
    pricing: perModality(
      ['文本输入', '$0.60/百万 tokens'],
      ['音频输出', '$12/百万 tokens'],
    ),
    limits: null,
    trainingParams: null,
    matchAliases: ['gpt-4o-mini-tts'],
    events: [
      { kind: 'api_available', occurredOn: '2025-03-20', title: 'Audio API 扩充:4o-transcribe / mini-transcribe / mini-tts 上线', sourceUrl: CL('2025-03-20') },
    ],
  },
  {
    provider: 'openai',
    officialId: 'tts-1',
    name: 'TTS-1',
    kind: 'audio_speech',
    stage: 'ga',
    availability: ['api'],
    summary: '速度优化的语音合成模型',
    sources: [
      { title: 'TTS-1 模型文档', url: DOC('tts-1') },
      PRICING_PAGE,
    ],
    pricing: price([{ text: '$15/百万字符', scope: null }]),
    limits: null,
    trainingParams: null,
    matchAliases: ['tts-1'],
    events: [
      { kind: 'api_available', occurredOn: '2023-11-06', title: 'DevDay 发布:文字转语音 API(tts-1 / tts-1-hd)', sourceUrl: CL('2023-11-06') },
    ],
  },
  {
    provider: 'openai',
    officialId: 'tts-1-hd',
    name: 'TTS-1 HD',
    kind: 'audio_speech',
    stage: 'ga',
    availability: ['api'],
    summary: '质量优化的语音合成模型',
    sources: [
      { title: 'TTS-1 HD 模型文档', url: DOC('tts-1-hd') },
      PRICING_PAGE,
    ],
    pricing: price([{ text: '$30/百万字符', scope: null }]),
    limits: null,
    trainingParams: null,
    matchAliases: ['tts-1-hd'],
    events: [
      { kind: 'api_available', occurredOn: '2023-11-06', title: 'DevDay 发布:文字转语音 API(tts-1 / tts-1-hd)', sourceUrl: CL('2023-11-06') },
    ],
  },
  {
    provider: 'openai',
    officialId: 'whisper-1',
    name: 'Whisper',
    kind: 'audio_speech',
    stage: 'ga',
    availability: ['api'],
    summary: '通用语音识别模型(开源 Whisper 的 API 版)',
    sources: [
      { title: 'Whisper 模型文档', url: DOC('whisper-1') },
      PRICING_PAGE,
    ],
    pricing: price([{ text: '$0.006/分钟', scope: null }]),
    limits: null,
    trainingParams: null,
    matchAliases: ['whisper-1'],
    events: [], // 初始发布(2022)早于 changelog 覆盖,不回填
  },
  // ---- 图像生成 ----
  {
    provider: 'openai',
    officialId: 'gpt-image-2',
    name: 'GPT-Image-2',
    kind: 'image_generation',
    stage: 'ga',
    availability: ['api'],
    summary: '最先进图像生成模型:灵活尺寸、高保真图像输入、token 计价、Batch 半价',
    sources: [
      { title: 'GPT-Image-2 模型文档', url: DOC('gpt-image-2') },
      PRICING_PAGE,
      CHANGELOG_PAGE,
    ],
    pricing: perModality(
      ['图像输入', '$8/百万 tokens(缓存 $2)'],
      ['文本输入', '$5/百万 tokens(缓存 $1.25)'],
      ['图像输出', '$30/百万 tokens'],
    ),
    limits: null,
    trainingParams: null,
    matchAliases: ['gpt-image-2'],
    events: [
      { kind: 'api_available', occurredOn: '2026-04-21', title: 'GPT Image 2 上线', sourceUrl: CL('2026-04-21') },
      { kind: 'updated', occurredOn: '2026-08-20', title: '透明背景预览支持(png/webp)', sourceUrl: CL('2026-08-20') },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-image-1.5',
    name: 'GPT-Image-1.5',
    kind: 'image_generation',
    stage: 'deprecated',
    availability: ['api'],
    summary: '上一代图像生成模型;已宣布弃用',
    sources: [
      { title: 'GPT-Image-1.5 模型文档', url: DOC('gpt-image-1.5') },
      PRICING_PAGE,
      DEPRECATIONS_PAGE,
    ],
    pricing: perModality(
      ['图像输入', '$8/百万 tokens(缓存 $2)'],
      ['文本输入', '$5/百万 tokens(缓存 $1.25)'],
      ['图像输出', '$32/百万 tokens'],
    ),
    limits: null,
    trainingParams: null,
    matchAliases: ['gpt-image-1.5'],
    events: [
      { kind: 'api_available', occurredOn: '2025-12-16', title: 'gpt-image-1.5 与 chatgpt-image-latest 发布', sourceUrl: CL('2025-12-16') },
      { kind: 'deprecated', occurredOn: '2026-06-02', title: '弃用公告:2026-12-01 关停(替代 gpt-image-2)', sourceUrl: DEPRECATIONS_PAGE.url },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-image-1',
    name: 'GPT-Image-1',
    kind: 'image_generation',
    stage: 'deprecated',
    availability: ['api'],
    summary: '上一代图像生成模型:质量与指令遵循提升;已宣布弃用',
    sources: [
      { title: 'GPT-Image-1 模型文档', url: DOC('gpt-image-1') },
      PRICING_PAGE,
      DEPRECATIONS_PAGE,
    ],
    pricing: perModality(
      ['图像输入', '$10/百万 tokens(缓存 $2.50)'],
      ['文本输入', '$5/百万 tokens(缓存 $1.25)'],
      ['图像输出', '$40/百万 tokens'],
    ),
    limits: null,
    trainingParams: null,
    matchAliases: ['gpt-image-1'],
    events: [
      { kind: 'api_available', occurredOn: '2025-04-23', title: 'gpt-image-1 上线', sourceUrl: CL('2025-04-23') },
      { kind: 'deprecated', occurredOn: '2026-04-22', title: '弃用公告:2026-10-23 关停(替代 gpt-image-2)', sourceUrl: DEPRECATIONS_PAGE.url },
    ],
  },
  {
    provider: 'openai',
    officialId: 'gpt-image-1-mini',
    name: 'GPT-Image-1 Mini',
    kind: 'image_generation',
    stage: 'deprecated',
    availability: ['api'],
    summary: '成本优化的图像生成模型;已宣布弃用',
    sources: [
      { title: 'GPT-Image-1 Mini 模型文档', url: DOC('gpt-image-1-mini') },
      PRICING_PAGE,
      DEPRECATIONS_PAGE,
    ],
    pricing: perModality(
      ['图像输入', '$2.50/百万 tokens(缓存 $0.25)'],
      ['文本输入', '$2/百万 tokens(缓存 $0.20)'],
      ['图像输出', '$8/百万 tokens'],
    ),
    limits: null,
    trainingParams: null,
    matchAliases: ['gpt-image-1-mini'],
    events: [
      { kind: 'api_available', occurredOn: '2025-10-06', title: 'DevDay 发布:gpt-image-1-mini 上线', sourceUrl: CL('2025-10-06') },
      { kind: 'deprecated', occurredOn: '2026-06-02', title: '弃用公告:2026-12-01 关停(替代 gpt-image-2)', sourceUrl: DEPRECATIONS_PAGE.url },
    ],
  },
  {
    provider: 'openai',
    officialId: 'dall-e-3',
    name: 'DALL·E 3',
    kind: 'image_generation',
    stage: 'retired',
    availability: ['api'],
    summary: '上一代图像生成模型;2026-05-12 已关停',
    sources: [
      { title: 'DALL·E 3 模型文档', url: DOC('dall-e-3') },
      DEPRECATIONS_PAGE,
    ],
    pricing: null,
    limits: null,
    trainingParams: null,
    matchAliases: ['dall-e-3'],
    events: [
      { kind: 'api_available', occurredOn: '2023-11-06', title: 'DevDay 发布:DALL·E 3 进入 API', sourceUrl: CL('2023-11-06') },
      { kind: 'deprecated', occurredOn: '2025-11-14', title: '弃用公告:2026-05-12 关停(替代 gpt-image-2)', sourceUrl: DEPRECATIONS_PAGE.url },
      { kind: 'retired', occurredOn: '2026-05-12', title: '已从 API 关停', sourceUrl: DEPRECATIONS_PAGE.url },
    ],
  },
  {
    provider: 'openai',
    officialId: 'dall-e-2',
    name: 'DALL·E 2',
    kind: 'image_generation',
    stage: 'retired',
    availability: ['api'],
    summary: '初代 API 图像生成模型;2026-05-12 已关停',
    sources: [
      { title: 'DALL·E 2 模型文档', url: DOC('dall-e-2') },
      DEPRECATIONS_PAGE,
    ],
    pricing: null,
    limits: null,
    trainingParams: null,
    matchAliases: ['dall-e-2'],
    events: [
      { kind: 'deprecated', occurredOn: '2025-11-14', title: '弃用公告:2026-05-12 关停(替代 gpt-image-2)', sourceUrl: DEPRECATIONS_PAGE.url },
      { kind: 'retired', occurredOn: '2026-05-12', title: '已从 API 关停', sourceUrl: DEPRECATIONS_PAGE.url },
    ],
  },
  // ---- 视频生成 ----
  {
    provider: 'openai',
    officialId: 'sora-2',
    name: 'Sora 2',
    kind: 'video_generation',
    stage: 'deprecated',
    availability: ['api', 'first_party_app'],
    summary: '旗舰视频生成模型:同步音频,720p;已宣布弃用',
    sources: [
      { title: 'Sora 2 模型文档', url: DOC('sora-2') },
      PRICING_PAGE,
      DEPRECATIONS_PAGE,
    ],
    pricing: price([{ text: '$0.10/秒', scope: '720p' }]),
    limits: null,
    trainingParams: null,
    matchAliases: ['sora-2'],
    events: [
      { kind: 'first_party_available', occurredOn: '2025-09-30', title: 'Sora 2 发布:Sora App 与 ChatGPT 内上线', sourceUrl: 'https://openai.com/index/sora-2' },
      { kind: 'api_available', occurredOn: '2025-10-06', title: 'DevDay 发布:Videos API 上线(Sora 2 / Sora 2 Pro)', sourceUrl: CL('2025-10-06') },
      { kind: 'updated', occurredOn: '2026-03-12', title: 'Sora API 扩充:角色参考、20 秒时长、视频扩展、Batch 支持', sourceUrl: CL('2026-03-12') },
      { kind: 'deprecated', occurredOn: '2026-03-24', title: '弃用公告:2026-09-24 随 Videos API 一并关停', sourceUrl: DEPRECATIONS_PAGE.url },
    ],
  },
  {
    provider: 'openai',
    officialId: 'sora-2-pro',
    name: 'Sora 2 Pro',
    kind: 'video_generation',
    stage: 'deprecated',
    availability: ['api'],
    summary: '最强同步音频视频生成模型(720p/1024p/1080p);已宣布弃用',
    sources: [
      { title: 'Sora 2 Pro 模型文档', url: DOC('sora-2-pro') },
      PRICING_PAGE,
      DEPRECATIONS_PAGE,
    ],
    pricing: price([
      { text: '$0.30/秒', scope: '720p' },
      { text: '$0.50/秒', scope: '1024p' },
      { text: '$0.70/秒', scope: '1080p' },
    ]),
    limits: null,
    trainingParams: null,
    matchAliases: ['sora-2-pro'],
    events: [
      { kind: 'api_available', occurredOn: '2025-10-06', title: 'DevDay 发布:Videos API 上线(Sora 2 / Sora 2 Pro)', sourceUrl: CL('2025-10-06') },
      { kind: 'updated', occurredOn: '2026-03-12', title: 'Sora API 扩充:角色参考、20 秒时长、1080p 输出、视频扩展、Batch 支持', sourceUrl: CL('2026-03-12') },
      { kind: 'deprecated', occurredOn: '2026-03-24', title: '弃用公告:2026-09-24 随 Videos API 一并关停', sourceUrl: DEPRECATIONS_PAGE.url },
    ],
  },
  // ---- 向量 ----
  {
    provider: 'openai',
    officialId: 'text-embedding-3-large',
    name: 'text-embedding-3-large',
    kind: 'embedding',
    stage: 'ga',
    availability: ['api'],
    summary: '最强 embedding 模型',
    sources: [
      { title: 'text-embedding-3-large 模型文档', url: DOC('text-embedding-3-large') },
      PRICING_PAGE,
      CHANGELOG_PAGE,
    ],
    pricing: price([{ text: '$0.13/百万 tokens', scope: null }]),
    limits: null,
    trainingParams: null,
    matchAliases: ['text-embedding-3-large'],
    events: [
      { kind: 'api_available', occurredOn: '2024-01-25', title: '新一代 embedding 模型上线(v3 large/small)', sourceUrl: CL('2024-01-25') },
    ],
  },
  {
    provider: 'openai',
    officialId: 'text-embedding-3-small',
    name: 'text-embedding-3-small',
    kind: 'embedding',
    stage: 'ga',
    availability: ['api'],
    summary: '小型 embedding 模型',
    sources: [
      { title: 'text-embedding-3-small 模型文档', url: DOC('text-embedding-3-small') },
      PRICING_PAGE,
      CHANGELOG_PAGE,
    ],
    pricing: price([{ text: '$0.02/百万 tokens', scope: null }]),
    limits: null,
    trainingParams: null,
    matchAliases: ['text-embedding-3-small'],
    events: [
      { kind: 'api_available', occurredOn: '2024-01-25', title: '新一代 embedding 模型上线(v3 large/small)', sourceUrl: CL('2024-01-25') },
    ],
  },
  {
    provider: 'openai',
    officialId: 'text-embedding-ada-002',
    name: 'text-embedding-ada-002',
    kind: 'embedding',
    stage: 'ga',
    availability: ['api'],
    summary: '上一代 embedding 模型',
    sources: [
      { title: 'text-embedding-ada-002 模型文档', url: DOC('text-embedding-ada-002') },
      PRICING_PAGE,
    ],
    pricing: price([{ text: '$0.10/百万 tokens', scope: null }]),
    limits: null,
    trainingParams: null,
    matchAliases: ['text-embedding-ada-002'],
    events: [], // 初始发布(2021)早于 changelog 覆盖,不回填
  },
  // ---- 审核/分类 ----
  {
    provider: 'openai',
    // 与 text-moderation 行同口径:基名立行,实际 API ID(-latest 移动别名)入 aliases
    officialId: 'omni-moderation',
    name: 'omni-moderation',
    kind: 'moderation_classification',
    stage: 'ga',
    availability: ['api'],
    summary: '文本与图像有害内容识别模型(免费)',
    sources: [
      { title: 'omni-moderation 模型文档', url: DOC('omni-moderation-latest') },
      PRICING_PAGE,
      CHANGELOG_PAGE,
    ],
    pricing: price([{ text: '免费', scope: null }]),
    limits: null,
    trainingParams: null,
    matchAliases: ['omni-moderation-latest'],
    events: [
      { kind: 'api_available', occurredOn: '2024-09-26', title: 'omni-moderation-latest 上线(文本+图像审核)', sourceUrl: CL('2024-09-26') },
      { kind: 'updated', occurredOn: '2026-06-04', title: '新增审核分数(moderation scores)', sourceUrl: CL('2026-06-04') },
    ],
  },
  {
    provider: 'openai',
    officialId: 'text-moderation',
    name: 'text-moderation',
    kind: 'moderation_classification',
    stage: 'retired',
    availability: ['api'],
    summary: '上一代纯文本审核模型(latest/stable 别名与 text-moderation-007 快照归并此行);2025-10-27 已关停',
    sources: [
      { title: 'text-moderation 模型文档', url: DOC('text-moderation-latest') },
      DEPRECATIONS_PAGE,
    ],
    pricing: null,
    limits: null,
    trainingParams: null,
    matchAliases: ['text-moderation-latest', 'text-moderation-stable', 'text-moderation-007'],
    events: [
      { kind: 'deprecated', occurredOn: '2025-04-28', title: '弃用公告:2025-10-27 关停(替代 omni-moderation)', sourceUrl: DEPRECATIONS_PAGE.url },
      { kind: 'retired', occurredOn: '2025-10-27', title: '已从 API 关停', sourceUrl: DEPRECATIONS_PAGE.url },
    ],
  },
]
