import type { ModelLimit, ModelPricing } from 'chrome-tab-shared'
import type { BaselineModel } from './modelTracking'

/**
 * 智谱人工核验基线(issues/02:八类全量)。全部资料于 2026-08-25 自官方一手信源核对:
 * - 模型清单/上下文/最大输出:模型广场 docs.bigmodel.cn/cn/guide/start/model-overview.md
 * - 价格(元/人民币,按量):官方价格页 open.bigmodel.cn/pricing(JS 渲染页,核对日快照)
 *   及各模型文档页明示价(如 GLM-Image 0.1 元/次、GLM-OCR 0.2 元/百万 tokens)
 * - 动态(上线/弃用日期):新品发布 docs.bigmodel.cn/cn/update/new-releases.md 与
 *   模型广场「即将弃用模型」表
 * - 开放权重:HuggingFace 官方 org zai-org 实仓核验
 * 排除第三方托管模型(视频生成 Vidu Q1/Vidu 2,平台接入非智谱自研,研究 §5)。
 * 归并规则(issues/02):独立命名变体分立成行;日期快照(GLM-4-Flash-250414 等)归并
 * 家族行;GLM-5.3 权重官方承诺「上线两周后放出」,核对日尚未发布,开放方式仅 API。
 */

/** 价格页/平台作用域(全部现价均为中国大陆开放平台人民币价)。 */
const CN = '中国大陆开放平台(bigmodel.cn)'
const PRICING_PAGE = { title: '官方价格页', url: 'https://open.bigmodel.cn/pricing' }
const OVERVIEW_PAGE = { title: '模型广场', url: 'https://docs.bigmodel.cn/cn/guide/start/model-overview.md' }
const RELEASES_PAGE = { title: '新品发布', url: 'https://docs.bigmodel.cn/cn/update/new-releases.md' }
const DOC = (slug: string) => `https://docs.bigmodel.cn${slug}`
/** 开放权重信源(HuggingFace 官方 zai-org 实仓)。 */
const HF = (repo: string) => ({ title: `开放权重(HuggingFace zai-org/${repo})`, url: `https://huggingface.co/zai-org/${repo}` })

const price = (entries: ModelPricing['entries']): ModelPricing => ({ region: CN, effectiveFrom: null, entries })
const perM = (input: string, output: string, scope: string | null = null) =>
  price([{ text: `输入 ${input} 元/百万 tokens`, scope }, { text: `输出 ${output} 元/百万 tokens`, scope }])
/** 「上下文/最大输出」限额对(目录口径)。 */
const ctx = (context: string, maxOut: string): ModelLimit[] => [
  { label: '上下文窗口', text: context, scope: null },
  { label: '最大输出', text: maxOut, scope: null },
]

export const ZHIPU_BASELINE: BaselineModel[] = [
  // ---- 文本(模型广场「文本模型」表 + 其他模型区)----
  {
    provider: 'zhipu',
    officialId: 'glm-5.3',
    name: 'GLM-5.3',
    kind: 'text',
    stage: 'ga',
    availability: ['api'], // 权重官方承诺上线两周后放出(2026-08-19 发布,核对日 08-25 尚未发布)
    summary: '智谱新一代旗舰模型:编程与长程任务能力增强,白盒安全审查能力涌现',
    sources: [
      { title: 'GLM-5.3 模型文档', url: DOC('/cn/guide/models/text/glm-5.3') },
      { title: 'GLM-5.3 发布文章(z.ai)', url: 'https://z.ai/blog/glm-5.3' },
      PRICING_PAGE,
    ],
    pricing: perM('8', '28'),
    limits: ctx('1M', '128K'),
    trainingParams: null, // 官方仅称「与 GLM-5.2 同基座,提升全来自后训练」,基座规模未披露
    matchAliases: ['GLM-5.3'],
    matchSlugs: ['/guide/models/text/glm-5.3'],
    events: [
      { kind: 'api_available', occurredOn: '2026-08-19', title: 'GLM-5.3 新一代旗舰模型上线', sourceUrl: DOC('/cn/guide/models/text/glm-5.3') },
    ],
  },
  {
    provider: 'zhipu',
    officialId: 'glm-5.2',
    name: 'GLM-5.2',
    kind: 'text',
    stage: 'ga',
    availability: ['api', 'open_weights'],
    summary: '1M 上下文,支撑复杂长程任务稳定执行;Coding 能力开源 SOTA',
    sources: [
      { title: 'GLM-5.2 模型文档', url: DOC('/cn/guide/models/text/glm-5.2') },
      PRICING_PAGE,
      HF('GLM-5.2'),
    ],
    pricing: perM('8', '28'),
    limits: ctx('1M', '128K'),
    trainingParams: null,
    matchAliases: ['GLM-5.2'],
    matchSlugs: ['/guide/models/text/glm-5.2'],
    events: [
      { kind: 'api_available', occurredOn: '2026-06-16', title: 'GLM-5.2 新一代旗舰模型上线', sourceUrl: DOC('/cn/guide/models/text/glm-5.2') },
    ],
  },
  {
    provider: 'zhipu',
    officialId: 'glm-5.1',
    name: 'GLM-5.1',
    kind: 'text',
    stage: 'ga',
    availability: ['api', 'open_weights'],
    summary: 'Coding 能力对齐 Claude Opus 4.6,长程任务可自主工作长达 8 小时',
    sources: [
      { title: 'GLM-5.1 模型文档', url: DOC('/cn/guide/models/text/glm-5.1') },
      PRICING_PAGE,
      HF('GLM-5.1'),
    ],
    pricing: price([
      { text: '输入 6 元/百万 tokens', scope: '输入长度 [0, 32)' },
      { text: '输出 24 元/百万 tokens', scope: '输入长度 [0, 32)' },
      { text: '输入 8 元/百万 tokens', scope: '输入长度 [32+)' },
      { text: '输出 28 元/百万 tokens', scope: '输入长度 [32+)' },
    ]),
    limits: ctx('200K', '128K'),
    trainingParams: null,
    matchAliases: ['GLM-5.1'],
    matchSlugs: ['/guide/models/text/glm-5.1'],
    events: [
      { kind: 'api_available', occurredOn: '2026-04-07', title: 'GLM-5.1 新一代旗舰模型上线', sourceUrl: DOC('/cn/guide/models/text/glm-5.1') },
    ],
  },
  {
    provider: 'zhipu',
    officialId: 'glm-5',
    name: 'GLM-5',
    kind: 'text',
    stage: 'ga',
    availability: ['api', 'open_weights'],
    summary: '编程能力对齐 Claude Opus 4.5,擅长 Agentic 长程规划与执行',
    sources: [
      { title: 'GLM-5 模型文档', url: DOC('/cn/guide/models/text/glm-5') },
      PRICING_PAGE,
      HF('GLM-5'),
    ],
    pricing: price([
      { text: '输入 4 元/百万 tokens', scope: '输入长度 [0, 32)' },
      { text: '输出 18 元/百万 tokens', scope: '输入长度 [0, 32)' },
      { text: '输入 6 元/百万 tokens', scope: '输入长度 [32+)' },
      { text: '输出 22 元/百万 tokens', scope: '输入长度 [32+)' },
    ]),
    limits: ctx('200K', '128K'),
    trainingParams: '744B(激活 40B)', // 模型文档「参数规模扩展:从 355B(激活 32B)扩展至 744B(激活 40B)」
    matchAliases: ['GLM-5'],
    matchSlugs: ['/guide/models/text/glm-5'],
    events: [
      { kind: 'api_available', occurredOn: '2026-02-12', title: 'GLM-5 新一代旗舰模型上线', sourceUrl: DOC('/cn/guide/models/text/glm-5') },
    ],
  },
  {
    provider: 'zhipu',
    officialId: 'glm-5-turbo',
    name: 'GLM-5-Turbo',
    kind: 'text',
    stage: 'ga',
    availability: ['api'],
    summary: '龙虾任务核心需求专项优化,复杂长任务执行连续性好',
    sources: [
      { title: 'GLM-5-Turbo 模型文档', url: DOC('/cn/guide/models/text/glm-5-turbo') },
      PRICING_PAGE,
    ],
    pricing: price([
      { text: '输入 5 元/百万 tokens', scope: '输入长度 [0, 32)' },
      { text: '输出 22 元/百万 tokens', scope: '输入长度 [0, 32)' },
      { text: '输入 7 元/百万 tokens', scope: '输入长度 [32+)' },
      { text: '输出 26 元/百万 tokens', scope: '输入长度 [32+)' },
    ]),
    limits: ctx('200K', '128K'),
    trainingParams: null,
    matchAliases: ['GLM-5-Turbo'],
    matchSlugs: ['/guide/models/text/glm-5-turbo'],
    events: [
      { kind: 'api_available', occurredOn: '2026-03-15', title: 'GLM-5-Turbo 龙虾增强基座模型上线', sourceUrl: DOC('/cn/guide/models/text/glm-5-turbo') },
    ],
  },
  {
    provider: 'zhipu',
    officialId: 'glm-4.7',
    name: 'GLM-4.7',
    kind: 'text',
    stage: 'ga',
    availability: ['api', 'open_weights'],
    summary: '通用对话、推理与智能体能力全面升级,编程更强、更稳、审美更好',
    sources: [
      { title: 'GLM-4.7 模型文档', url: DOC('/cn/guide/models/text/glm-4.7') },
      PRICING_PAGE,
      HF('GLM-4.7'),
    ],
    pricing: price([
      { text: '输入 2 元/百万 tokens', scope: '输入长度 [0, 32) · 输出长度 [0, 0.2)' },
      { text: '输出 8 元/百万 tokens', scope: '输入长度 [0, 32) · 输出长度 [0, 0.2)' },
      { text: '输入 3 元/百万 tokens', scope: '输入长度 [0, 32) · 输出长度 [0.2+)' },
      { text: '输出 14 元/百万 tokens', scope: '输入长度 [0, 32) · 输出长度 [0.2+)' },
      { text: '输入 4 元/百万 tokens', scope: '输入长度 [32, 200)' },
      { text: '输出 16 元/百万 tokens', scope: '输入长度 [32, 200)' },
    ]),
    limits: ctx('200K', '128K'),
    trainingParams: null,
    matchAliases: ['GLM-4.7'],
    matchSlugs: ['/guide/models/text/glm-4.7'],
    events: [
      { kind: 'api_available', occurredOn: '2025-12-22', title: 'GLM-4.7 基座模型上线', sourceUrl: DOC('/cn/guide/models/text/glm-4.7') },
    ],
  },
  {
    provider: 'zhipu',
    officialId: 'glm-4.7-flashx',
    name: 'GLM-4.7-FlashX',
    kind: 'text',
    stage: 'ga',
    availability: ['api'],
    summary: '轻量高速,小尺寸强能力,适用于中文写作、翻译、角色扮演等通用场景',
    sources: [
      { title: 'GLM-4.7 系列文档', url: DOC('/cn/guide/models/text/glm-4.7') },
      PRICING_PAGE,
    ],
    pricing: perM('0.5', '3'),
    limits: ctx('200K', '128K'),
    trainingParams: null,
    matchAliases: ['GLM-4.7-FlashX'],
    matchSlugs: ['/guide/models/text/glm-4.7'],
  },
  {
    provider: 'zhipu',
    officialId: 'glm-4.6',
    name: 'GLM-4.6',
    kind: 'text',
    stage: 'ga',
    availability: ['api', 'open_weights'],
    summary: '上下文提升至 200K,擅长高级编码、复杂推理与工具调用',
    sources: [
      { title: 'GLM-4.6 模型文档', url: DOC('/cn/guide/models/text/glm-4.6') },
      HF('GLM-4.6'),
    ],
    pricing: null, // 价格页旗舰区与历史区均未列现行 token 价(仅私有实例 200k-fp8 刊例)
    limits: ctx('200K', '128K'),
    trainingParams: null,
    matchAliases: ['GLM-4.6'],
    matchSlugs: ['/guide/models/text/glm-4.6'],
    events: [
      { kind: 'api_available', occurredOn: '2025-09-30', title: 'GLM-4.6 基座模型上线', sourceUrl: DOC('/cn/guide/models/text/glm-4.6') },
    ],
  },
  {
    provider: 'zhipu',
    officialId: 'glm-4.5-air',
    name: 'GLM-4.5-Air',
    kind: 'text',
    stage: 'ga',
    availability: ['api', 'open_weights'],
    summary: '高性价比轻量模型,推理、编码与智能体任务表现稳定',
    sources: [
      { title: 'GLM-4.5 系列文档', url: DOC('/cn/guide/models/text/glm-4.5') },
      PRICING_PAGE,
      HF('GLM-4.5-Air'),
    ],
    pricing: price([
      { text: '输入 0.8 元/百万 tokens', scope: '输入长度 [0, 32) · 输出长度 [0, 0.2)' },
      { text: '输出 2 元/百万 tokens', scope: '输入长度 [0, 32) · 输出长度 [0, 0.2)' },
      { text: '输入 0.8 元/百万 tokens', scope: '输入长度 [0, 32) · 输出长度 [0.2+)' },
      { text: '输出 6 元/百万 tokens', scope: '输入长度 [0, 32) · 输出长度 [0.2+)' },
      { text: '输入 1.2 元/百万 tokens', scope: '输入长度 [32, 128)' },
      { text: '输出 8 元/百万 tokens', scope: '输入长度 [32, 128)' },
    ]),
    limits: ctx('128K', '96K'),
    trainingParams: null,
    matchAliases: ['GLM-4.5-Air'],
    matchSlugs: ['/guide/models/text/glm-4.5'],
  },
  {
    provider: 'zhipu',
    officialId: 'glm-4.5-airx',
    name: 'GLM-4.5-AirX',
    kind: 'text',
    stage: 'ga',
    availability: ['api'],
    summary: '高性价比极速版本,适合低延迟、高响应要求的业务场景',
    sources: [{ title: 'GLM-4.5 系列文档', url: DOC('/cn/guide/models/text/glm-4.5') }],
    pricing: null, // 价格页未列现行价(历史区 GLM-4-AirX 为上一代,不冒认)
    limits: ctx('128K', '96K'),
    trainingParams: null,
    matchAliases: ['GLM-4.5-AirX'],
    matchSlugs: ['/guide/models/text/glm-4.5'],
  },
  {
    provider: 'zhipu',
    officialId: 'glm-4-long',
    name: 'GLM-4-Long',
    kind: 'text',
    stage: 'ga',
    availability: ['api'],
    summary: '支持高达 1M 上下文长度,为处理超长文本和记忆型任务设计',
    sources: [
      { title: 'GLM-4-Long 模型文档', url: DOC('/cn/guide/models/text/glm-4-long') },
      PRICING_PAGE,
    ],
    pricing: price([{ text: '1 元/百万 tokens', scope: null }]),
    limits: ctx('1M', '4K'),
    trainingParams: null,
    matchAliases: ['GLM-4-Long'],
    matchSlugs: ['/guide/models/text/glm-4-long'],
  },
  {
    provider: 'zhipu',
    officialId: 'glm-4.7-flash',
    name: 'GLM-4.7-Flash',
    kind: 'text',
    stage: 'ga',
    availability: ['api', 'open_weights'],
    summary: '免费模型,延续 GLM-4.7 基座的通用能力',
    sources: [
      { title: 'GLM-4.7-Flash 模型文档', url: DOC('/cn/guide/models/free/glm-4.7-flash') },
      PRICING_PAGE,
      HF('GLM-4.7-Flash'),
    ],
    pricing: price([{ text: '免费', scope: null }]),
    limits: ctx('200K', '128K'),
    trainingParams: null,
    matchAliases: ['GLM-4.7-Flash'],
    matchSlugs: ['/guide/models/free/glm-4.7-flash'],
    events: [
      { kind: 'api_available', occurredOn: '2026-01-19', title: 'GLM-4.7-Flash 免费模型上线', sourceUrl: DOC('/cn/guide/models/free/glm-4.7-flash') },
    ],
  },
  {
    provider: 'zhipu',
    officialId: 'glm-4.5-flash',
    name: 'GLM-4.5-Flash',
    kind: 'text',
    stage: 'deprecated', // 模型广场标注「即将下线」
    availability: ['api'],
    summary: '免费模型,支持深度思考模式与最长 128K 上下文(模型广场标注即将下线)',
    sources: [{ title: 'GLM-4.5-Flash 模型文档', url: DOC('/cn/guide/models/free/glm-4.5-flash') }],
    pricing: price([{ text: '免费', scope: null }]),
    limits: ctx('128K', '96K'),
    trainingParams: null,
    matchAliases: ['GLM-4.5-Flash'],
    matchSlugs: ['/guide/models/free/glm-4.5-flash'],
  },
  {
    provider: 'zhipu',
    officialId: 'glm-4-flashx',
    name: 'GLM-4-FlashX',
    kind: 'text',
    stage: 'ga',
    availability: ['api'],
    summary: 'Flash 增强高速版本,推理速度快,适合高并发调用场景(日期快照 -250414 归并本行)',
    sources: [
      { title: 'GLM-4 系列文档', url: DOC('/cn/guide/models/text/glm-4') },
      PRICING_PAGE,
    ],
    pricing: price([{ text: '0.1 元/百万 tokens', scope: null }]),
    limits: ctx('128K', '16K'),
    trainingParams: null,
    matchAliases: ['GLM-4-FlashX', 'GLM-4-FlashX-250414'],
    matchSlugs: ['/guide/models/text/glm-4'],
  },
  {
    provider: 'zhipu',
    officialId: 'glm-4-flash',
    name: 'GLM-4-Flash',
    kind: 'text',
    stage: 'ga',
    availability: ['api'],
    summary: '免费模型,支持长上下文处理,适合多语言理解与工具调用场景(日期快照 -250414 归并本行)',
    sources: [{ title: 'GLM-4 系列文档', url: DOC('/cn/guide/models/text/glm-4') }],
    pricing: price([{ text: '免费', scope: null }]),
    limits: ctx('128K', '16K'),
    trainingParams: null,
    matchAliases: ['GLM-4-Flash', 'GLM-4-Flash-250414'],
    matchSlugs: ['/guide/models/text/glm-4'],
    events: [
      { kind: 'api_available', occurredOn: '2025-04-14', title: 'GLM-4-Flash-250414(免费版)上线', sourceUrl: RELEASES_PAGE.url },
    ],
  },
  {
    provider: 'zhipu',
    officialId: 'charglm-4',
    name: 'CharGLM-4',
    kind: 'text',
    stage: 'ga',
    availability: ['api'],
    summary: '拟人对话模型,适合情感陪伴与虚拟角色互动',
    sources: [OVERVIEW_PAGE, PRICING_PAGE],
    pricing: price([{ text: '1 元/百万 tokens', scope: null }]),
    limits: ctx('8K', '4K'),
    trainingParams: null,
    matchAliases: ['CharGLM-4'],
    matchSlugs: [],
  },
  {
    provider: 'zhipu',
    officialId: 'emohaa',
    name: 'Emohaa',
    kind: 'text',
    stage: 'ga',
    availability: ['api'],
    summary: '心理情感支持模型,具备专业咨询与情绪疏导能力(GLM 架构)',
    sources: [OVERVIEW_PAGE, PRICING_PAGE],
    pricing: price([{ text: '15 元/百万 tokens', scope: null }]),
    limits: ctx('8K', '4K'),
    trainingParams: null,
    matchAliases: ['Emohaa'],
    matchSlugs: [],
  },
  {
    provider: 'zhipu',
    officialId: 'codegeex-4',
    name: 'CodeGeeX-4',
    kind: 'text',
    stage: 'ga',
    availability: ['api'],
    summary: '代码补全模型,适用于代码自动补全与开发辅助',
    sources: [OVERVIEW_PAGE, PRICING_PAGE],
    pricing: price([{ text: '0.1 元/百万 tokens', scope: null }]),
    limits: ctx('128K', '32K'),
    trainingParams: null,
    matchAliases: ['CodeGeeX-4'],
    matchSlugs: [],
  },
  // ---- 多模态理解(模型广场「视觉模型」表)----
  {
    provider: 'zhipu',
    officialId: 'glm-5v-turbo',
    name: 'GLM-5V-Turbo',
    kind: 'multimodal_understanding',
    stage: 'ga',
    availability: ['api'],
    summary: '多模态 Coding 基座,兼顾视觉理解、推理与代码生成,适配 Agent 工作流',
    sources: [
      { title: 'GLM-5V-Turbo 模型文档', url: DOC('/cn/guide/models/vlm/glm-5v-turbo') },
      PRICING_PAGE,
    ],
    pricing: price([
      { text: '输入 5 元/百万 tokens', scope: '输入长度 [0, 32)' },
      { text: '输出 22 元/百万 tokens', scope: '输入长度 [0, 32)' },
      { text: '输入 7 元/百万 tokens', scope: '输入长度 [32+)' },
      { text: '输出 26 元/百万 tokens', scope: '输入长度 [32+)' },
    ]),
    limits: ctx('200K', '128K'),
    trainingParams: null, // 官方仅称「更小参数量下实现更优性能」,具体规模未披露
    matchAliases: ['GLM-5V-Turbo'],
    matchSlugs: ['/guide/models/vlm/glm-5v-turbo'],
    events: [
      { kind: 'api_available', occurredOn: '2026-04-02', title: 'GLM-5V-Turbo 多模态 Coding 基座模型上线', sourceUrl: DOC('/cn/guide/models/vlm/glm-5v-turbo') },
    ],
  },
  {
    provider: 'zhipu',
    officialId: 'glm-4.6v',
    name: 'GLM-4.6V',
    kind: 'multimodal_understanding',
    stage: 'ga',
    availability: ['api', 'open_weights'],
    summary: '视觉推理能力增强,原生支持工具调用与长上下文,前端代码复刻效果更稳定',
    sources: [
      { title: 'GLM-4.6V 模型文档', url: DOC('/cn/guide/models/vlm/glm-4.6v') },
      PRICING_PAGE,
      HF('GLM-4.6V'),
    ],
    pricing: price([
      { text: '输入 1 元/百万 tokens', scope: '输入长度 [0, 32)' },
      { text: '输出 3 元/百万 tokens', scope: '输入长度 [0, 32)' },
      { text: '输入 2 元/百万 tokens', scope: '输入长度 [32, 128)' },
      { text: '输出 6 元/百万 tokens', scope: '输入长度 [32, 128)' },
    ]),
    limits: ctx('128K', '32K'),
    trainingParams: '106B(激活 12B)',
    matchAliases: ['GLM-4.6V'],
    matchSlugs: ['/guide/models/vlm/glm-4.6v'],
    events: [
      { kind: 'api_available', occurredOn: '2025-12-08', title: 'GLM-4.6V 视觉推理模型上线', sourceUrl: DOC('/cn/guide/models/vlm/glm-4.6v') },
    ],
  },
  {
    provider: 'zhipu',
    officialId: 'glm-4.6v-flashx',
    name: 'GLM-4.6V-FlashX',
    kind: 'multimodal_understanding',
    stage: 'ga',
    availability: ['api'],
    summary: 'GLM-4.6V 系列轻量高速版(模型广场目录未列,价格页在售)',
    sources: [
      { title: 'GLM-4.6V 系列文档', url: DOC('/cn/guide/models/vlm/glm-4.6v') },
      PRICING_PAGE,
    ],
    pricing: price([
      { text: '输入 0.15 元/百万 tokens', scope: '输入长度 [0, 32)' },
      { text: '输出 1.5 元/百万 tokens', scope: '输入长度 [0, 32)' },
      { text: '输入 0.3 元/百万 tokens', scope: '输入长度 [32, 128)' },
      { text: '输出 3 元/百万 tokens', scope: '输入长度 [32, 128)' },
    ]),
    limits: null,
    trainingParams: null,
    matchAliases: ['GLM-4.6V-FlashX'],
    matchSlugs: ['/guide/models/vlm/glm-4.6v'],
  },
  {
    provider: 'zhipu',
    officialId: 'glm-ocr',
    name: 'GLM-OCR',
    kind: 'multimodal_understanding',
    stage: 'ga',
    availability: ['api', 'open_weights'],
    summary: '轻量图文解析模型,兼顾高精度、高效率文档理解,支持常见复杂版式解析',
    sources: [
      { title: 'GLM-OCR 模型文档', url: DOC('/cn/guide/models/vlm/glm-ocr') },
      HF('GLM-OCR'),
    ],
    pricing: price([{ text: '0.2 元/百万 tokens(输入输出同价)', scope: null }]),
    limits: [
      { label: '输入', text: '单图 ≤ 10 MB;PDF ≤ 50 MB;最大支持 100 页', scope: null },
    ],
    trainingParams: '0.9B',
    matchAliases: ['GLM-OCR'],
    matchSlugs: ['/guide/models/vlm/glm-ocr'],
    events: [
      { kind: 'api_available', occurredOn: '2026-02-03', title: 'GLM-OCR 图文解析模型上线', sourceUrl: DOC('/cn/guide/models/vlm/glm-ocr') },
    ],
  },
  {
    provider: 'zhipu',
    officialId: 'autoglm-phone',
    name: 'AutoGLM-Phone',
    kind: 'multimodal_understanding',
    stage: 'ga',
    availability: ['api'],
    summary: '手机智能助理框架,自然语言完成 App 操作任务,覆盖完整移动端操作指令集',
    sources: [{ title: 'AutoGLM-Phone 模型文档', url: DOC('/cn/guide/models/vlm/autoglm-phone') }],
    pricing: null,
    limits: ctx('20K', '2048'),
    trainingParams: null,
    matchAliases: ['AutoGLM-Phone'],
    matchSlugs: ['/guide/models/vlm/autoglm-phone'],
    events: [
      { kind: 'api_available', occurredOn: '2025-12-11', title: 'AutoGLM-Phone AI 手机智能助理框架上线', sourceUrl: DOC('/cn/guide/models/vlm/autoglm-phone') },
    ],
  },
  {
    provider: 'zhipu',
    officialId: 'glm-4.1v-thinking-flashx',
    name: 'GLM-4.1V-Thinking-FlashX',
    kind: 'multimodal_understanding',
    stage: 'ga',
    availability: ['api'],
    summary: '轻量视觉推理模型,擅长复杂场景理解与多步骤分析,适合高并发视觉推理场景',
    sources: [{ title: 'GLM-4.1V-Thinking 系列文档', url: DOC('/cn/guide/models/vlm/glm-4.1v-thinking') }],
    pricing: null,
    limits: ctx('64K', '16K'),
    trainingParams: null,
    matchAliases: ['GLM-4.1V-Thinking-FlashX'],
    matchSlugs: ['/guide/models/vlm/glm-4.1v-thinking'],
    events: [
      { kind: 'api_available', occurredOn: '2025-07-02', title: 'GLM-4.1V-Thinking 系列视觉推理模型上线', sourceUrl: DOC('/cn/guide/models/vlm/glm-4.1v-thinking') },
    ],
  },
  {
    provider: 'zhipu',
    officialId: 'glm-4.6v-flash',
    name: 'GLM-4.6V-Flash',
    kind: 'multimodal_understanding',
    stage: 'ga',
    availability: ['api', 'open_weights'],
    summary: '免费模型,支持视觉推理与长上下文,可灵活开关思考模式',
    sources: [
      { title: 'GLM-4.6V-Flash 模型文档', url: DOC('/cn/guide/models/free/glm-4.6v-flash') },
      PRICING_PAGE,
      HF('GLM-4.6V-Flash'),
    ],
    pricing: price([{ text: '免费', scope: null }]),
    limits: ctx('128K', '32K'),
    trainingParams: '9B',
    matchAliases: ['GLM-4.6V-Flash'],
    matchSlugs: ['/guide/models/free/glm-4.6v-flash'],
  },
  {
    provider: 'zhipu',
    officialId: 'glm-4.1v-thinking-flash',
    name: 'GLM-4.1V-Thinking-Flash',
    kind: 'multimodal_understanding',
    stage: 'ga',
    availability: ['api'],
    summary: '免费模型,擅长复杂场景理解与多步骤分析,适合通用多模态理解任务',
    sources: [{ title: 'GLM-4.1V-Thinking-Flash 模型文档', url: DOC('/cn/guide/models/free/glm-4.1v-thinking-flash') }],
    pricing: price([{ text: '免费', scope: null }]),
    limits: ctx('64K', '16K'),
    trainingParams: null,
    matchAliases: ['GLM-4.1V-Thinking-Flash'],
    matchSlugs: ['/guide/models/free/glm-4.1v-thinking-flash', '/guide/models/vlm/glm-4.1v-thinking'],
    events: [
      { kind: 'api_available', occurredOn: '2025-07-02', title: 'GLM-4.1V-Thinking 系列视觉推理模型上线', sourceUrl: DOC('/cn/guide/models/vlm/glm-4.1v-thinking') },
    ],
  },
  {
    provider: 'zhipu',
    officialId: 'glm-4v-flash',
    name: 'GLM-4V-Flash',
    kind: 'multimodal_understanding',
    stage: 'ga',
    availability: ['api'],
    summary: '免费模型,具备基础多模态问答能力,适合轻量视觉理解场景',
    sources: [{ title: 'GLM-4V-Flash 模型文档', url: DOC('/cn/guide/models/free/glm-4v-flash') }],
    pricing: price([{ text: '免费', scope: null }]),
    limits: ctx('16K', '1K'),
    trainingParams: null,
    matchAliases: ['GLM-4V-Flash'],
    matchSlugs: ['/guide/models/free/glm-4v-flash'],
  },
  // ---- 图像生成 ----
  {
    provider: 'zhipu',
    officialId: 'glm-image',
    name: 'GLM-Image',
    kind: 'image_generation',
    stage: 'ga',
    availability: ['api'],
    summary: '旗舰图像生成模型,复杂指令遵循与知识密集生成更强,汉字文字渲染尤其出色',
    sources: [{ title: 'GLM-Image 模型文档', url: DOC('/cn/guide/models/image-generation/glm-image') }],
    pricing: price([{ text: '0.1 元/次', scope: null }]),
    limits: [{ label: '分辨率', text: '支持多分辨率', scope: null }],
    trainingParams: null,
    matchAliases: ['GLM-Image'],
    matchSlugs: ['/guide/models/image-generation/glm-image'],
    events: [
      // 发布页原块误链 glm-4.7 文档页(已知张冠李戴),信源按人工核验修正为 GLM-Image 文档页
      { kind: 'api_available', occurredOn: '2026-01-14', title: 'GLM-Image 图像生成模型上线', sourceUrl: DOC('/cn/guide/models/image-generation/glm-image') },
    ],
  },
  {
    provider: 'zhipu',
    officialId: 'cogview-4',
    name: 'CogView-4',
    kind: 'image_generation',
    stage: 'ga',
    availability: ['api'],
    summary: '通用图像生成模型,生成质量高,风格表达丰富多样',
    sources: [
      { title: 'CogView-4 模型文档', url: DOC('/cn/guide/models/image-generation/cogview-4') },
      PRICING_PAGE,
    ],
    pricing: price([{ text: '0.06 元/次', scope: null }]),
    limits: [{ label: '分辨率', text: '支持多分辨率', scope: null }],
    trainingParams: null,
    matchAliases: ['CogView-4'],
    matchSlugs: ['/guide/models/image-generation/cogview-4'],
  },
  {
    provider: 'zhipu',
    officialId: 'cogview-3-flash',
    name: 'CogView-3-Flash',
    kind: 'image_generation',
    stage: 'ga',
    availability: ['api'],
    summary: '免费模型,生成速度快,适合轻量图像创作',
    sources: [{ title: 'CogView-3-Flash 模型文档', url: DOC('/cn/guide/models/free/cogview-3-flash') }],
    pricing: price([{ text: '免费', scope: null }]),
    limits: [{ label: '分辨率', text: '支持多分辨率', scope: null }],
    trainingParams: null,
    matchAliases: ['CogView-3-Flash'],
    matchSlugs: ['/guide/models/free/cogview-3-flash'],
  },
  // ---- 视频生成(Vidu Q1/Vidu 2 为平台托管的第三方,不纳入)----
  {
    provider: 'zhipu',
    officialId: 'cogvideox-3',
    name: 'CogVideoX-3',
    kind: 'video_generation',
    stage: 'ga',
    availability: ['api'],
    summary: '高智能旗舰视频模型,画质、指令遵循与物理模拟更强,支持首尾帧生成',
    sources: [
      { title: 'CogVideoX-3 模型文档', url: DOC('/cn/guide/models/video-generation/cogvideox-3') },
      PRICING_PAGE,
    ],
    pricing: price([{ text: '1 元/次', scope: null }]),
    limits: [{ label: '分辨率', text: '支持多分辨率', scope: null }],
    trainingParams: null,
    matchAliases: ['CogVideoX-3'],
    matchSlugs: ['/guide/models/video-generation/cogvideox-3'],
    events: [
      { kind: 'api_available', occurredOn: '2025-07-15', title: 'CogVideoX-3 视频生成模型上线', sourceUrl: DOC('/cn/guide/models/video-generation/cogvideox-3') },
    ],
  },
  {
    provider: 'zhipu',
    officialId: 'cogvideox-flash',
    name: 'CogVideoX-Flash',
    kind: 'video_generation',
    stage: 'ga',
    availability: ['api'],
    summary: '免费模型,支持 AI 音效、4K 画质与 60fps,最长 10 秒视频生成',
    sources: [{ title: 'CogVideoX-Flash 模型文档', url: DOC('/cn/guide/models/free/cogvideox-flash') }],
    pricing: price([{ text: '免费', scope: null }]),
    limits: [{ label: '分辨率', text: '支持多分辨率', scope: null }],
    trainingParams: null,
    matchAliases: ['CogVideoX-Flash'],
    matchSlugs: ['/guide/models/free/cogvideox-flash'],
  },
  // ---- 音频/语音 ----
  {
    provider: 'zhipu',
    officialId: 'glm-tts',
    name: 'GLM-TTS',
    kind: 'audio_speech',
    stage: 'ga',
    availability: ['api', 'open_weights'],
    summary: '语音合成模型,超拟人语音生成与情感表达,首帧响应低于 400ms',
    sources: [
      { title: 'GLM-TTS 模型文档', url: DOC('/cn/guide/models/sound-and-video/glm-tts') },
      PRICING_PAGE,
      HF('GLM-TTS'),
    ],
    pricing: price([{ text: '¥4 / 万次对话', scope: '价格页计费名 CogTTS' }]),
    limits: null,
    trainingParams: null,
    matchAliases: ['GLM-TTS', 'CogTTS'],
    matchSlugs: ['/guide/models/sound-and-video/glm-tts'],
    events: [
      { kind: 'api_available', occurredOn: '2025-12-11', title: 'GLM-TTS 语音合成模型上线', sourceUrl: DOC('/cn/guide/models/sound-and-video/glm-tts') },
    ],
  },
  {
    provider: 'zhipu',
    officialId: 'glm-tts-clone',
    name: 'GLM-TTS-Clone',
    kind: 'audio_speech',
    stage: 'ga',
    availability: ['api'],
    summary: '音色克隆模型,3 秒音频即可快速生成相似音色,支持普通话与细腻情感表达',
    sources: [
      { title: 'GLM-TTS-Clone 模型文档', url: DOC('/cn/guide/models/sound-and-video/glm-tts-clone') },
      PRICING_PAGE,
    ],
    pricing: price([{ text: '¥6 / 次', scope: '价格页计费名 CogTTS-Clone' }]),
    limits: null,
    trainingParams: null,
    matchAliases: ['GLM-TTS-Clone'],
    matchSlugs: ['/guide/models/sound-and-video/glm-tts-clone'],
    events: [
      { kind: 'api_available', occurredOn: '2025-12-11', title: 'GLM-TTS-Clone 音色克隆模型上线', sourceUrl: DOC('/cn/guide/models/sound-and-video/glm-tts-clone') },
    ],
  },
  {
    provider: 'zhipu',
    officialId: 'glm-asr-2512',
    name: 'GLM-ASR-2512',
    kind: 'audio_speech',
    stage: 'ga',
    availability: ['api'],
    summary: '高精度语音识别模型,字符错误率 0.0717,支持自定义词汇、多语言与方言',
    sources: [
      { title: 'GLM-ASR-2512 模型文档', url: DOC('/cn/guide/models/sound-and-video/glm-asr-2512') },
      PRICING_PAGE,
    ],
    pricing: price([{ text: '¥0.06 / 分钟', scope: '价格页计费名 GLM-ASR' }]),
    limits: [{ label: '上传文件', text: '文件 ≤ 25 MB;音频时长 ≤ 30 秒', scope: null }],
    trainingParams: null,
    matchAliases: ['GLM-ASR-2512'],
    matchSlugs: ['/guide/models/sound-and-video/glm-asr-2512'],
    events: [
      { kind: 'api_available', occurredOn: '2025-12-10', title: 'GLM-ASR-2512 语音识别模型上线', sourceUrl: DOC('/cn/guide/models/sound-and-video/glm-asr-2512') },
    ],
  },
  {
    provider: 'zhipu',
    officialId: 'glm-realtime-flash',
    name: 'GLM-Realtime-Flash',
    kind: 'audio_speech',
    stage: 'ga',
    availability: ['api'],
    summary: '实时音视频模型(GLM-Realtime-Flash),支持视频通话与长时对话记忆',
    sources: [{ title: 'GLM-Realtime 模型文档', url: DOC('/cn/guide/models/sound-and-video/glm-realtime') }],
    pricing: price([{ text: '音频 0.18 元/分钟;视频 1.2 元/分钟', scope: null }]),
    limits: [
      { label: '上下文窗口', text: '8K(预计 20 轮)', scope: '音频通话' },
      { label: '上下文窗口', text: '32K', scope: '视频通话' },
      { label: '最大输出', text: '1K', scope: null },
    ],
    trainingParams: null,
    matchAliases: ['GLM-Realtime-Flash'],
    matchSlugs: ['/guide/models/sound-and-video/glm-realtime'],
  },
  {
    provider: 'zhipu',
    officialId: 'glm-realtime-air',
    name: 'GLM-Realtime-Air',
    kind: 'audio_speech',
    stage: 'ga',
    availability: ['api'],
    summary: '实时音视频模型(GLM-Realtime-Air),跨文本、音频和视频的实时推理',
    sources: [{ title: 'GLM-Realtime 模型文档', url: DOC('/cn/guide/models/sound-and-video/glm-realtime') }],
    pricing: price([{ text: '音频 0.3 元/分钟;视频 2.1 元/分钟', scope: null }]),
    limits: [
      { label: '上下文窗口', text: '8K(预计 20 轮)', scope: '音频通话' },
      { label: '上下文窗口', text: '32K', scope: '视频通话' },
      { label: '最大输出', text: '1K', scope: null },
    ],
    trainingParams: null,
    matchAliases: ['GLM-Realtime-Air'],
    matchSlugs: ['/guide/models/sound-and-video/glm-realtime'],
  },
  {
    provider: 'zhipu',
    officialId: 'glm-4-voice',
    name: 'GLM-4-Voice',
    kind: 'audio_speech',
    stage: 'ga',
    availability: ['api'],
    summary: '实时语音对话模型,中英文语音理解与生成,可按指令调情感、语调、语速和方言',
    sources: [
      { title: 'GLM-4-Voice 模型文档', url: DOC('/cn/guide/models/sound-and-video/glm-4-voice') },
      PRICING_PAGE,
    ],
    pricing: price([{ text: '¥80 / 百万 tokens', scope: null }]),
    limits: null,
    trainingParams: null,
    matchAliases: ['GLM-4-Voice'],
    matchSlugs: ['/guide/models/sound-and-video/glm-4-voice'],
  },
  // ---- 向量 ----
  {
    provider: 'zhipu',
    officialId: 'embedding-3',
    name: 'Embedding-3',
    kind: 'embedding',
    stage: 'ga',
    availability: ['api'],
    summary: '向量模型 V3,构建语义检索增强、聚类、主题建模与分类',
    sources: [
      { title: 'Embedding-3 模型文档', url: DOC('/cn/guide/models/embedding/embedding-3') },
      PRICING_PAGE,
    ],
    pricing: price([{ text: '0.5 元/百万 tokens', scope: null }]),
    limits: [{ label: '上下文窗口', text: '8K', scope: null }],
    trainingParams: null,
    matchAliases: ['Embedding-3'],
    matchSlugs: ['/guide/models/embedding/embedding-3'],
  },
  {
    provider: 'zhipu',
    officialId: 'embedding-2',
    name: 'Embedding-2',
    kind: 'embedding',
    stage: 'ga',
    availability: ['api'],
    summary: '向量模型 V2',
    sources: [
      { title: 'Embedding-2 模型文档', url: DOC('/cn/guide/models/embedding/embedding-2') },
      PRICING_PAGE,
    ],
    pricing: price([{ text: '0.5 元/百万 tokens', scope: null }]),
    limits: [{ label: '上下文窗口', text: '8K', scope: null }],
    trainingParams: null,
    matchAliases: ['Embedding-2'],
    matchSlugs: ['/guide/models/embedding/embedding-2'],
  },
  // ---- 重排 ----
  {
    provider: 'zhipu',
    officialId: 'rerank',
    name: 'Rerank',
    kind: 'rerank',
    stage: 'ga',
    availability: ['api'],
    summary: '文本重排序模型,计算文本相关性 score 值,优化召回结果排序与匹配效果',
    sources: [
      { title: '文本重排序 API 参考', url: 'https://docs.bigmodel.cn/api-reference/模型-api/文本重排序' },
      PRICING_PAGE,
    ],
    pricing: price([{ text: '0.8 元/百万 tokens', scope: null }]),
    limits: [{ label: '上下文窗口', text: '4K', scope: null }],
    trainingParams: null,
    matchAliases: ['Rerank'],
    matchSlugs: [],
  },
  // ---- 审核/分类 ----
  {
    provider: 'zhipu',
    officialId: 'moderation',
    name: '内容安全(moderation)',
    kind: 'moderation_classification',
    stage: 'ga',
    availability: ['api'],
    summary: '内容安全审核,覆盖文本、图片、音频、视频的风险识别,输出结构化审核结果',
    sources: [{ title: '内容安全 API 参考', url: 'https://docs.bigmodel.cn/api-reference/工具-api/内容安全' }],
    pricing: null,
    limits: [{ label: '文本输入', text: '最大 2000 字符', scope: null }],
    trainingParams: null,
    matchAliases: ['内容安全'],
    matchSlugs: [],
  },
  // ---- 已退役(模型广场「即将弃用模型」表,弃用日均已过生效)----
  {
    provider: 'zhipu',
    officialId: 'glm-z1',
    name: 'GLM-Z1 系列',
    kind: 'text',
    stage: 'retired',
    availability: [],
    summary: 'GLM-Z1 推理模型系列(AirX/Air/Flash),2025-11-15 弃用生效',
    sources: [OVERVIEW_PAGE, RELEASES_PAGE],
    pricing: null,
    limits: null,
    trainingParams: null,
    matchAliases: ['GLM-Z1'],
    matchSlugs: ['/guide/models/text/glm-z1'],
    events: [
      { kind: 'api_available', occurredOn: '2025-04-14', title: 'GLM-Z1-AirX/Air/Flash 推理模型上线', sourceUrl: RELEASES_PAGE.url },
      { kind: 'retired', occurredOn: '2025-11-15', title: 'GLM-Z1 系列弃用生效', sourceUrl: OVERVIEW_PAGE.url },
    ],
  },
  {
    provider: 'zhipu',
    officialId: 'glm-4-0520',
    name: 'GLM-4-0520',
    kind: 'text',
    stage: 'retired',
    availability: [],
    summary: 'GLM-4-0520,2025-12-30 弃用生效',
    sources: [OVERVIEW_PAGE],
    pricing: null,
    limits: null,
    trainingParams: null,
    matchAliases: ['GLM-4-0520'],
    matchSlugs: [],
    events: [
      { kind: 'retired', occurredOn: '2025-12-30', title: 'GLM-4-0520 弃用生效', sourceUrl: OVERVIEW_PAGE.url },
    ],
  },
]
